"""BASELINE-1 Am.1: the published baseline has a tool, and drift is a RED.

`.github/public-export-baseline.v0.json` is the one input the fences cannot
derive from this repository -- "was this document public before its prefix
became private" is a fact about the OTHER repository -- so it is a recorded
snapshot. A recorded snapshot has two failure modes and neither is visible by
reading the file.

* **Nobody can reproduce it.** A snapshot regenerated by a script that lives in
  somebody's scratch directory is a number with no instrument behind it: the
  next actor either trusts it or rebuilds the generator from the shape of the
  output. `scripts/regen_public_baseline.py` is that generator, committed, and
  the first test below rebuilds a fixture clone's baseline through it and
  compares against a golden written out BYTE BY BYTE in this file -- not
  against another call of the tool, which would only prove the tool agrees
  with itself.
* **It goes stale silently, and stale hides in the safe-looking direction.**
  `classify_path` consults `public_paths` before `new_private_prefixes`, so a
  baseline older than the published tree DROPS already-published documents from
  the population the fences walk. The fences then pass on a smaller world. The
  ancestry check is the cheapest true statement available without a second
  export: the recorded commit must be an ancestor of the published tip. It
  cannot prove the baseline is CURRENT -- only a regeneration can -- but it
  catches the two ways it goes wrong in practice, a tip that has moved past the
  recording and a recording taken against a different history.

The ancestry check needs the other repository, so it runs when the rehearsal
declares its fresh clone in `FLOATI_PUBLIC_ROOT` and is silent otherwise. Silent
is not the same as absent: a declared root that is not a clone refuses.
"""

from __future__ import annotations

import importlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from tests.private_artifacts import require_private_artifact


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

SCRIPT = REPOSITORY_ROOT / "scripts" / "regen_public_baseline.py"
BASELINE_RELATIVE = ".github/public-export-baseline.v0.json"

#: The files this module needs in a tree the exporter shaped. The export
#: excludes `.github/` instruments (the baseline among them) and ships `tests/`
#: and `scripts/`; a reader who downloads the projection runs this module
#: without the baseline file, so the module must be green there, not only here.
SHIPPED_DEPENDENCIES = (
    "tests/__init__.py",
    "tests/export_inventory.py",
    "tests/private_artifacts.py",
    "tests/test_public_export_baseline.py",
    "tests/fixtures/baseline-1-f1/public-export-baseline.v0.json",
    "scripts/regen_public_baseline.py",
)

#: Set in the child of the projection-shape test below, so the module it copies
#: does not recurse into building another projection of itself.
PROJECTION_SHAPE_CHILD_ENV = "FLOATI_PROJECTION_SHAPE_CHILD"
FIXTURE_PATHS = (
    ".github/workflows/selftest.yml",
    "AGENTS.md",
    "README.md",
    "docs/DESIGN.md",
)


def git(root: Path, *arguments: str) -> str:
    environment = {
        key: value for key, value in os.environ.items() if not key.startswith("GIT_")
    }
    completed = subprocess.run(
        ["/usr/bin/git", *arguments],
        cwd=root,
        env=environment,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def make_public_clone(root: Path) -> str:
    """A stand-in for the published repository: a few committed paths, one tip."""

    root.mkdir(parents=True)
    git(root, "init", "-q", "--initial-branch=main")
    git(root, "config", "user.name", "fixture")
    git(root, "config", "user.email", "fixture@example.invalid")
    for relative in FIXTURE_PATHS:
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f"body of {relative}\n", encoding="utf-8")
    git(root, "add", ".")
    git(root, "commit", "-q", "-m", "public tree")
    return git(root, "rev-parse", "HEAD")


def golden_document(commit: str, relatives: tuple[str, ...]) -> str:
    """The expected bytes, written out here rather than produced by the tool.

    Key order, indent, the trailing newline and the absence of a trailing comma
    are all part of what "byte-identical to the committed file" means, so they
    are spelled rather than delegated to a second `json.dumps`.
    """

    ordered = sorted(relatives)
    lines = ["{", f'  "public_commit": "{commit}",', '  "public_paths": [']
    for index, relative in enumerate(ordered):
        comma = "," if index < len(ordered) - 1 else ""
        lines.append(f'    "{relative}"{comma}')
    lines.extend(["  ],", '  "schema_version": 0', "}"])
    return "\n".join(lines) + "\n"


def write_baseline(root: Path, commit: str, relatives: tuple[str, ...]) -> Path:
    target = root / BASELINE_RELATIVE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(golden_document(commit, relatives), encoding="utf-8")
    return target


def regenerator():
    return importlib.import_module("scripts.regen_public_baseline")


def run_tool(*arguments: str) -> subprocess.CompletedProcess[str]:
    environment = {
        key: value for key, value in os.environ.items() if not key.startswith("GIT_")
    }
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    return subprocess.run(
        [sys.executable, str(SCRIPT), *arguments],
        cwd=REPOSITORY_ROOT,
        env=environment,
        check=False,
        capture_output=True,
        text=True,
    )


class RegeneratorBytesTests(unittest.TestCase):
    def test_regenerates_a_fixture_clone_byte_for_byte(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            public = scratch / "public"
            head = make_public_clone(public)
            out = scratch / "baseline.json"
            completed = run_tool(
                "--public-root",
                str(public),
                "--public-commit",
                head,
                "--out",
                str(out),
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertEqual(
                out.read_text(encoding="utf-8"), golden_document(head, FIXTURE_PATHS)
            )
            artifact = json.loads(completed.stdout)
            self.assertEqual(artifact["status"], "ok")
            self.assertEqual(artifact["evidence"]["public_commit"], head)
            self.assertEqual(artifact["evidence"]["path_count"], len(FIXTURE_PATHS))

    def test_derives_the_public_commit_from_the_clone_head_and_says_so(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            public = scratch / "public"
            head = make_public_clone(public)
            out = scratch / "baseline.json"
            completed = run_tool("--public-root", str(public), "--out", str(out))
            self.assertEqual(completed.returncode, 0, completed.stderr)
            artifact = json.loads(completed.stdout)
            self.assertEqual(artifact["evidence"]["public_commit"], head)
            self.assertEqual(artifact["evidence"]["public_commit_source"], "clone-head")
            self.assertEqual(
                out.read_text(encoding="utf-8"), golden_document(head, FIXTURE_PATHS)
            )

    def test_refuses_a_dirty_public_clone(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            public = scratch / "public"
            head = make_public_clone(public)
            (public / "README.md").write_text("edited in place\n", encoding="utf-8")
            completed = run_tool(
                "--public-root",
                str(public),
                "--public-commit",
                head,
                "--out",
                str(scratch / "baseline.json"),
            )
            self.assertEqual(completed.returncode, 20)
            evidence = json.loads(completed.stdout)["evidence"]
            self.assertEqual(evidence["code"], "public_export_baseline_clone_dirty")
            self.assertIn("README.md", evidence["detail"])
            self.assertIn("git -C", evidence["remedy"])
            self.assertFalse((scratch / "baseline.json").exists())

    def test_refuses_a_commit_the_clone_does_not_contain(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            public = scratch / "public"
            make_public_clone(public)
            absent = "d" * 40
            completed = run_tool(
                "--public-root",
                str(public),
                "--public-commit",
                absent,
                "--out",
                str(scratch / "baseline.json"),
            )
            self.assertEqual(completed.returncode, 20)
            evidence = json.loads(completed.stdout)["evidence"]
            self.assertEqual(
                evidence["code"], "public_export_baseline_commit_unresolved"
            )
            self.assertIn(absent, evidence["detail"])
            self.assertTrue(evidence["remedy"])
            self.assertFalse((scratch / "baseline.json").exists())

    def test_usage_names_the_three_arguments(self) -> None:
        completed = run_tool("--help")
        self.assertEqual(completed.returncode, 0, completed.stderr)
        for flag in ("--public-root", "--public-commit", "--out"):
            self.assertIn(flag, completed.stdout)


class AncestryTests(unittest.TestCase):
    def test_an_ancestor_recording_is_accepted(self) -> None:
        module = regenerator()
        with tempfile.TemporaryDirectory() as raw:
            public = Path(raw) / "public"
            recorded = make_public_clone(public)
            (public / "README.md").write_text("a later export\n", encoding="utf-8")
            git(public, "add", ".")
            git(public, "commit", "-q", "-m", "a later export")
            tip = git(public, "rev-parse", "HEAD")
            self.assertEqual(
                module.assert_public_commit_current(public, recorded, "HEAD"), tip
            )

    def test_a_non_ancestor_recording_refuses_naming_both_commits(self) -> None:
        module = regenerator()
        with tempfile.TemporaryDirectory() as raw:
            public = Path(raw) / "public"
            make_public_clone(public)
            git(public, "checkout", "-q", "--orphan", "sideways")
            (public / "README.md").write_text("a different history\n", encoding="utf-8")
            git(public, "add", ".")
            git(public, "commit", "-q", "-m", "a different history")
            stranger = git(public, "rev-parse", "HEAD")
            git(public, "checkout", "-q", "main")
            tip = git(public, "rev-parse", "HEAD")
            with self.assertRaises(module.BaselineRefusal) as caught:
                module.assert_public_commit_current(public, stranger, "HEAD")
            refusal = caught.exception
            self.assertEqual(refusal.code, "public_export_baseline_stale")
            self.assertIn(stranger, refusal.detail)
            self.assertIn(tip, refusal.detail)
            self.assertIn("regen_public_baseline.py", refusal.remedy)
            self.assertIn("--public-root", refusal.remedy)

    def test_a_recording_absent_from_the_clone_refuses(self) -> None:
        module = regenerator()
        with tempfile.TemporaryDirectory() as raw:
            public = Path(raw) / "public"
            make_public_clone(public)
            absent = "e" * 40
            with self.assertRaises(module.BaselineRefusal) as caught:
                module.assert_public_commit_current(public, absent, "HEAD")
            self.assertEqual(
                caught.exception.code, "public_export_baseline_commit_unresolved"
            )
            self.assertIn(absent, caught.exception.detail)
            self.assertTrue(caught.exception.remedy)


class FenceWiringTests(unittest.TestCase):
    """The drift check where the fences read the baseline, not beside it."""

    def setUp(self) -> None:
        self.inventory = importlib.import_module("tests.export_inventory")
        self.previous = os.environ.get(self.inventory.PUBLIC_ROOT_ENV)
        self.addCleanup(self._restore)

    def _restore(self) -> None:
        if self.previous is None:
            os.environ.pop(self.inventory.PUBLIC_ROOT_ENV, None)
        else:
            os.environ[self.inventory.PUBLIC_ROOT_ENV] = self.previous

    def test_published_baseline_passes_on_the_real_pair(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            public = scratch / "public"
            recorded = make_public_clone(public)
            harbor = scratch / "harbor"
            write_baseline(harbor, recorded, FIXTURE_PATHS)
            os.environ[self.inventory.PUBLIC_ROOT_ENV] = str(public)
            self.assertEqual(
                self.inventory.published_baseline(harbor), frozenset(FIXTURE_PATHS)
            )

    def test_published_baseline_reds_when_the_recording_is_not_an_ancestor(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            public = scratch / "public"
            make_public_clone(public)
            git(public, "checkout", "-q", "--orphan", "sideways")
            (public / "README.md").write_text("a different history\n", encoding="utf-8")
            git(public, "add", ".")
            git(public, "commit", "-q", "-m", "a different history")
            stranger = git(public, "rev-parse", "HEAD")
            git(public, "checkout", "-q", "main")
            harbor = scratch / "harbor"
            write_baseline(harbor, stranger, FIXTURE_PATHS)
            os.environ[self.inventory.PUBLIC_ROOT_ENV] = str(public)
            module = regenerator()
            with self.assertRaises(module.BaselineRefusal) as caught:
                self.inventory.published_baseline(harbor)
            self.assertEqual(caught.exception.code, "public_export_baseline_stale")

    def test_an_undeclared_clone_leaves_the_baseline_readable(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            harbor = Path(raw) / "harbor"
            write_baseline(harbor, "f" * 40, FIXTURE_PATHS)
            os.environ.pop(self.inventory.PUBLIC_ROOT_ENV, None)
            self.assertEqual(
                self.inventory.published_baseline(harbor), frozenset(FIXTURE_PATHS)
            )

    def test_a_declared_root_that_is_not_a_clone_refuses(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            harbor = scratch / "harbor"
            write_baseline(harbor, "f" * 40, FIXTURE_PATHS)
            empty = scratch / "not-a-clone"
            empty.mkdir()
            os.environ[self.inventory.PUBLIC_ROOT_ENV] = str(empty)
            module = regenerator()
            with self.assertRaises(module.BaselineRefusal) as caught:
                self.inventory.published_baseline(harbor)
            self.assertEqual(caught.exception.code, "public_export_baseline_root_invalid")


class CompanionFixtureTests(unittest.TestCase):
    """BASELINE-1-F1 Am.1: the two copies cannot drift apart through a regen.

    The refusal (16:04Z, measured by perturbation): `regen_public_baseline.py`
    wrote only its `--out`, so the stage-7 regeneration that follows every
    export rewrote the committed baseline and left the shipped fixture behind --
    and `test_the_committed_baseline_file_matches_the_shipped_fixture` reds
    main within the hour of the next export. The keeper has to live in the
    regenerator, not in an operator's memory.
    """

    def test_rewriting_the_committed_baseline_rewrites_the_fixture_in_the_same_act(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as raw:
            scratch = Path(raw)
            public = scratch / "public"
            recorded = make_public_clone(public)
            # The published tree moves past the recording, the way an export does.
            (public / "docs" / "NEW.md").parent.mkdir(parents=True, exist_ok=True)
            (public / "docs" / "NEW.md").write_text("a later export\n", encoding="utf-8")
            git(public, "add", ".")
            git(public, "commit", "-q", "-m", "a later export")
            later = git(public, "rev-parse", "HEAD")
            later_paths = FIXTURE_PATHS + ("docs/NEW.md",)
            # A repository-shaped tree carrying the pair, both stale.
            harbor = scratch / "harbor"
            committed = write_baseline(harbor, recorded, FIXTURE_PATHS)
            fixture = harbor / "tests/fixtures/baseline-1-f1/public-export-baseline.v0.json"
            fixture.parent.mkdir(parents=True, exist_ok=True)
            fixture.write_bytes(committed.read_bytes())
            completed = run_tool(
                "--public-root", str(public), "--out", str(committed)
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            expected = golden_document(later, later_paths)
            self.assertEqual(committed.read_text(encoding="utf-8"), expected)
            self.assertEqual(
                fixture.read_text(encoding="utf-8"),
                expected,
                "the regenerator rewrote the committed baseline and left the "
                "shipped fixture behind: the two-copy invariant reds on the "
                "next export",
            )


class ProjectionShapeTests(unittest.TestCase):
    """The module must be green in the tree a reader can actually download.

    BASELINE-1-F1: the `2045b2aa` rehearsal was RED on exactly one error --
    this module's committed-file test read `.github/public-export-baseline.v0.json`,
    which the export excludes by policy, so the projected suite ERRORED while
    the harbor suite was green. Neither the push fence nor the harbor run can
    see that: only the projection can, and the projection is the product.

    This test builds a synthetic projection -- this module and its shipped
    dependencies under a scratch root, with the baseline file absent -- and
    runs the WHOLE module there. What it CANNOT see: the synthetic tree is
    hand-shaped, so it assumes the export excludes the baseline and ships the
    dependencies named above; it does not run the exporter's own classifier or
    fences. That half is the rehearsal's to prove. A new import added to this
    module turns this test RED until the dependency list grows with it.
    """

    def test_the_module_is_green_where_the_export_leaves_the_baseline_behind(self) -> None:
        if os.environ.get(PROJECTION_SHAPE_CHILD_ENV):
            self.skipTest("child of a projection-shape run; not this test's subject")
        with tempfile.TemporaryDirectory() as raw:
            projected = Path(raw) / "projected"
            for relative in SHIPPED_DEPENDENCIES:
                target = projected / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(REPOSITORY_ROOT / relative, target)
            environment = {
                key: value
                for key, value in os.environ.items()
                if not key.startswith("GIT_")
            }
            environment["PYTHONDONTWRITEBYTECODE"] = "1"
            environment[PROJECTION_SHAPE_CHILD_ENV] = "1"
            completed = subprocess.run(
                [sys.executable, "-m", "unittest", "-v", "tests.test_public_export_baseline"],
                cwd=projected,
                env=environment,
                check=False,
                capture_output=True,
                text=True,
            )
            self.assertEqual(
                completed.returncode,
                0,
                "the projected tree errors on this module:\n"
                + completed.stderr
                + completed.stdout,
            )


class CommittedBaselineTests(unittest.TestCase):
    """The recorded snapshot, read where it lives and where it does not.

    `.github/public-export-baseline.v0.json` is a `private_only_path`, so the
    projection carries neither the file nor the check on it. FIXTURE-1's ruling
    (2026-09-05): a fixture a shipped test reads lives under `tests/fixtures/`,
    so the byte-shape check runs against a shipped copy everywhere, and the
    harbor-only comparison pins that copy to the committed file byte for byte.
    The two together say everything the old single test said, and the projection
    gets a stated skip instead of an error.
    """

    FIXTURE_RELATIVE = "tests/fixtures/baseline-1-f1/public-export-baseline.v0.json"

    def test_the_shipped_fixture_has_the_shape_the_tool_writes(self) -> None:
        text = (REPOSITORY_ROOT / self.FIXTURE_RELATIVE).read_text(encoding="utf-8")
        document = json.loads(text)
        self.assertEqual(
            text, golden_document(document["public_commit"], tuple(document["public_paths"]))
        )
        self.assertEqual(document["schema_version"], 0)

    def test_the_committed_baseline_file_matches_the_shipped_fixture(self) -> None:
        require_private_artifact(self, BASELINE_RELATIVE)
        self.assertEqual(
            (REPOSITORY_ROOT / BASELINE_RELATIVE).read_bytes(),
            (REPOSITORY_ROOT / self.FIXTURE_RELATIVE).read_bytes(),
            "the committed baseline moved; copy it to the shipped fixture in "
            "the same act, or the projection tests a snapshot the harbor no "
            "longer holds",
        )


if __name__ == "__main__":
    unittest.main()
