#!/usr/bin/env python3
"""Regenerate the two H1-F1 reader maps — the tool BASELINE-1's finding said we owed.

BASELINE-1's finding, in one sentence: **no committed tool owns a derived artifact**,
so the artifact is regenerated by hand, in a scratchpad, by whoever last needed it —
and the scratchpad dies with the session. The regenerator that repaired train BB's
union was written that way and is gone. This is that tool, banked.

WHY IT EXISTS AT ALL. The maps pin every reader of one needle **by file AND LINE**, so
they are invalidated by any commit that adds a line above a reader — *including a
commit that changes no code*. BB's baseline car added published paths, moved the needle
934 -> 936 inside two artifacts, and red three tests with nothing executable in the
diff. A `grep` cannot answer this: the question is never whether the string appears, it
is whether the CENSUS MOVED.

WHAT IT REFUSES TO DO. It derives nothing itself. Every row comes from
`tests.test_h1_f1`'s own `derive_readers`, and the two halves are split by that module's
own `included_reader_census` / `classify_inventory_excluded` — the same functions the
assertions use. A regenerator with its own copy of the derivation is a second opinion
about a derived value, which is the defect it exists to prevent.

    --check   compare only; exit 1 and print a unified diff per map. Run this on EVERY
              union, at the tip you are about to push, not at the union you composed.
    --write   rewrite both maps in place.

**--check is the default**, because a tool that writes by default gets run by accident.
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

PUBLIC_RELATIVE = "tests/h1_f1_reader_map.txt"
PRIVATE_RELATIVE = ".github/h1-f1-reader-map-private.v0.txt"


def render(rows) -> str:
    """The pin's on-disk form: `kind<TAB>path:line`, one row per line, in derived order."""

    return "".join("%s\t%s:%d\n" % (kind, path, line) for path, line, kind in rows)


def halves(root: Path):
    sys.path.insert(0, str(root))
    from tests.export_inventory import classify_inventory_excluded
    from tests.test_h1_f1 import derive_readers, included_reader_census, load_pin

    rows = derive_readers(root)
    kept_rows, _kept_pinned = included_reader_census(rows, load_pin(root), root)
    population = sorted({path for path, _line, _kind in rows})
    excluded = frozenset(classify_inventory_excluded(population, root=root))
    return kept_rows, [row for row in rows if row[0] in excluded]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="repository root (default: cwd)")
    parser.add_argument("--write", action="store_true", help="rewrite both maps in place")
    arguments = parser.parse_args()

    root = Path(arguments.root).resolve()
    public_rows, private_rows = halves(root)
    drift = 0
    for relative, rows in ((PUBLIC_RELATIVE, public_rows), (PRIVATE_RELATIVE, private_rows)):
        path = root / relative
        wanted = render(rows)
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if wanted == current:
            print("UNCHANGED %-44s %4d rows" % (relative, len(rows)))
            continue
        drift += 1
        if arguments.write:
            path.write_text(wanted, encoding="utf-8")
            print("WROTE     %-44s %4d rows" % (relative, len(rows)))
            continue
        print("DRIFT     %-44s %4d rows derived" % (relative, len(rows)))
        for line in difflib.unified_diff(
            current.splitlines(True), wanted.splitlines(True),
            fromfile="committed/" + relative, tofile="derived/" + relative,
        ):
            sys.stdout.write("    " + line)
    if drift and not arguments.write:
        print("\n%d map(s) drifted. Re-run with --write, then re-run --check at the tip you push."
              % drift)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
