"""Static, instant, man-page-quality help for every Phase B command."""

from __future__ import annotations

from typing import Dict, Optional, Sequence

from .copy import GH_AUTHENTICATION_REMEDY, register


def _page(name: str, synopsis: str, description: str, details: str, examples: str) -> str:
    return (
        f"NAME\n    {name}\n\n"
        f"SYNOPSIS\n    {synopsis}\n\n"
        f"DESCRIPTION\n    {description}\n\n"
        f"OPTIONS AND ARGUMENTS\n{details}\n\n"
        "EXIT STATUS\n"
        "    0 success; 20 refusal; 31 intentional silence; 32 no result;\n"
        "    33 malformed evidence; 34 orchestration deadline; 35 degraded;\n"
        "    36 sandbox write refused.\n"
        "    The artifact process status is authoritative.\n\n"
        f"EXAMPLES\n{examples}\n"
    )


_RAW: Dict[str, str] = {
    "": _page(
        "floati - inspect and operate an explicit fleet root",
        "floati COMMAND [OPTIONS]",
        "Operate the local receipt-ledger bus and orchestration log. Every durable command requires an explicit root.",
        "    Commands: describe, overlap, init, register, retire, node, role, context, chart, survey, wake, send,\n    verify, journal, signature, repair, inbox, ack, sent, log, status, snapshot, effects, effect, threads,\n    thread, graph, plan, doctor, watch, receipts, grant, work, intake, worker, sequencer,\n    supervise, mcp, board, orchestrate, epoch, install, update, uninstall, purge, quota. Use COMMAND --help for its contract.",
        "    floati status --root /absolute/fleet\n    floati effects --root /absolute/fleet\n    floati work --help",
    ),
    "describe": _page("floati describe - project the live command contract", "floati describe --json", "Project every registered command and argument from the same argparse objects the CLI executes.", "    --json   Required machine-readable schema-versioned artifact.\n    The projection is read-only and contains no hand-maintained command table.", "    floati describe --json"),
    "overlap": _page("floati overlap - derive local overlap evidence", "floati overlap {report} [OPTIONS]", "Derive advisory semantic-overlap evidence from one explicit local Git repository.", "    Subcommand: report. The command is read-only, opens no network connection, and never merges, cancels, or acquires a lock.", "    floati overlap report --help"),
    "overlap report": _page("floati overlap report - emit one local overlap fact", "floati overlap report --repository REPOSITORY --base-ref REF --left-ref REF --right-ref REF", "Emit the existing schema-v1 overlap report fact for two local refs against one explicit base.", "    --repository PATH   Exact canonical Git repository root.\n    --base-ref REF      Common comparison base resolved by local Git.\n    --left-ref REF      First local ref resolved by local Git.\n    --right-ref REF     Second local ref resolved by local Git.\n    MEASURED same-symbol and same-schema signals may inform a consumer; this verb remains advisory and read-only.", "    floati overlap report --repository /repo/floati --base-ref main --left-ref branch-a --right-ref branch-b"),
    "init": _page("floati init - create a direct fleet home", "floati init [--root ROOT] [--solo NODE [--harness HARNESS]] [--topology TOPOLOGY --coordinator NODE --coordinator-authority AUTH --owner-tier ITEM]", "Create or validate one explicit direct-home fleet root. Solo bootstrap registers one harness and a bounded work authority.", "    --root ROOT        Absolute direct-home path. Namespace roots are refused.\n    --solo NODE        Configure one unambiguous local work identity.\n    --harness HARNESS  Recorded harness role; default solo.\n    --topology TOPOLOGY           Declared fleet topology: star or mesh.\n    --coordinator NODE            The declared topology's coordinator node.\n    --coordinator-authority AUTH  Repeatable coordinator authority granted in writing: dispatch_bounded_work, gate_results_before_merge, decide_non_owner_tier_questions.\n    --owner-tier ITEM             Repeatable owner-tier list reserved to the human: publishing, credentials, key_custody.\n    The four governance flags are given together or not at all.", "    floati init --root ~/floati-demo\n    floati init --root ~/my-sessions --solo me --harness Codex"),
    "journal": _page("floati journal - exact-byte journal testimony", "floati journal {checkpoint|verify} [OPTIONS]", "Create and verify bounded exact-byte continuity checkpoints for an explicitly selected JSONL journal.", "    Subcommands: checkpoint, verify. Legacy lines remain unchanged and are named as pre-chain testimony.", "    floati journal verify --help"),
    "journal checkpoint": _page("floati journal checkpoint - write one bounded checkpoint", "floati journal checkpoint --root ROOT --journal PATH --journal-id ID --kind KIND [--kind KIND ...] --output PATH [--json]", "Measure the selected chained journal and durably replace one standalone checkpoint file inside its explicit root.", "    --journal and --output are root-relative paths. --kind is repeatable.\n    The checkpoint binds sequence, exact-line head digest, and byte length; it is not an authenticity or freshness proof.", "    floati journal checkpoint --root ~/fleet --journal receipts/events.jsonl --journal-id events --kind message_envelope --output checkpoints/events.json --json"),
    "journal verify": _page("floati journal verify - verify one bounded checkpoint", "floati journal verify --root ROOT --journal PATH --journal-id ID --kind KIND [--kind KIND ...] --checkpoint PATH [--historical] [--json]", "Verify exact-byte continuity through one checkpoint and retain the highest accepted sequence inside the explicit root.", "    --historical permits an older valid checkpoint without lowering retained rollback state.\n    Pre-chain history is anchored but carries typed absence of seq/prev testimony. A checkpoint alone cannot prove authenticity or freshness.", "    floati journal verify --root ~/fleet --journal receipts/events.jsonl --journal-id events --kind message_envelope --checkpoint checkpoints/events.json --json"),
    "repair": _page("floati repair - govern explicit ledger repair", "floati repair {quarantine} [OPTIONS]", "Repair one selected direct-home ledger through an evidence-preserving governed operation.", "    Subcommand: quarantine. Repair replaces the ledger inode and invalidates tail followers, waiters, and monitors.", "    floati repair quarantine --help"),
    "repair quarantine": _page("floati repair quarantine - quarantine one exact event frame", "floati repair quarantine --root ROOT --ledger events.jsonl --record-id ID --idempotency-key KEY", "Preserve one selected physical frame beneath the tenant and atomically replace the event ledger with retained frames plus a repair receipt.", "    --root ROOT             Existing explicit direct-home root.\n    --ledger events.jsonl   The only governed repair coordinate.\n    --record-id ID          Stable envelope id selecting exactly one frame.\n    --idempotency-key KEY   Stable retry key bound to the exact request.", "    floati repair quarantine --root ~/fleet --ledger events.jsonl --record-id msg-... --idempotency-key repair-1"),
    "epoch": _page("floati epoch - govern one whole bus epoch", "floati epoch {roll} [OPTIONS]", "Rotate the selected event, delivery, and acknowledgment ledgers as one governed epoch.", "    Subcommand: roll. The archived epoch remains byte-exact and live readers must rebuild from the replacement epoch.", "    floati epoch roll --help"),
    "epoch roll": _page("floati epoch roll - archive and replace one bus epoch", "floati epoch roll --root ROOT --as NODE --idempotency-key KEY", "Archive the selected ledger family and replace it with one closed roll receipt under exact active authority.", "    --root ROOT             Existing explicit direct-home root.\n    --as NODE               Exact active holder of bus-epoch-roll authority.\n    --idempotency-key KEY   Stable retry key bound to this actor and roll.\n    The archive path, span, digest, file count, and per-plane counts are derived from durable bytes.", "    floati epoch roll --root ~/fleet --as architect-a --idempotency-key epoch-roll-1"),
    "signature": _page("floati signature - Minisign artifact testimony", "floati signature {sign|verify} [OPTIONS]", "Create or verify one detached Minisign signature over explicit artifact bytes and a signed filename/version binding.", "    Subcommands: sign, verify. Floati never generates a release key and never fetches a public key.", "    floati signature verify --help"),
    "signature sign": _page("floati signature sign - sign one explicit artifact", "floati signature sign --root ROOT --artifact PATH --signature PATH --secret-key ABSOLUTE_PATH --version VERSION --minisign-executable ABSOLUTE_PATH [--journal-id ID --through-seq N] [--json]", "Ask one operator-declared Minisign binary to create a detached signature with a strict signed binding.", "    Artifact and signature paths stay inside ROOT. The secret key must be an existing absolute file outside ROOT.\n    Minisign must be an explicit canonical executable; Floati never resolves PATH. Omitting it is a named refusal with the declaration remedy.\n    Journal id and sequence are all-or-none. This command never generates, rotates, copies, or fetches a key.", "    floati signature sign --root ~/release --artifact floati.tar.gz --signature floati.tar.gz.minisig --secret-key /offline/release.key --version 2.0.0 --minisign-executable /usr/local/bin/minisign --json"),
    "signature verify": _page("floati signature verify - verify one explicit artifact", "floati signature verify --root ROOT --artifact PATH --signature PATH --public-key PATH --version VERSION --minisign-executable ABSOLUTE_PATH [--journal-id ID --through-seq N] [--json]", "Verify exact artifact bytes and compare the signed trusted-comment binding with one operator-declared Minisign binary.", "    All three files are explicit root-relative paths; no key or signature is fetched.\n    Minisign must be an explicit canonical executable; Floati never resolves PATH. Omitting it is a named refusal with the declaration remedy.\n    Journal id and sequence are all-or-none.", "    floati signature verify --root ~/release --artifact floati.tar.gz --signature floati.tar.gz.minisig --public-key trust/floati-release.pub --version 2.0.0 --minisign-executable /usr/local/bin/minisign --json"),
    "node": _page("floati node - node administration", "floati node {add|spawn|retire|switch|role|boot|teardown|explain|state-flush} [OPTIONS]", "Preview exact registry rows before committing lifecycle changes and project live node context without cached topology.", "    Subcommands: add, spawn, retire, switch, role, boot, teardown, explain, state-flush.", "    floati node add --root ~/fleet --node builder-a --harness Codex --lifetime permanent"),
    "node add": _page("floati node add - add one node", "floati node add --root ROOT --node NODE --harness HARNESS --lifetime permanent|temporary [--lease-minutes N] [--tide-metric METRIC --tide-threshold VALUE --tide-action recommend|direct]", "Preview and atomically commit an active registry row and optional lease, creating the nested workspace.", "    Temporary nodes require --lease-minutes; permanent nodes refuse it.\n    --tide-metric METRIC --tide-threshold VALUE --tide-action recommend|direct\n                          Optional Tide policy step for the node; the three are given together or not at all.\n    --tide-idempotency-key KEY  Keys the Tide policy append; generated when absent.", "    floati node add --root ~/fleet --node builder-a --harness Codex --lifetime temporary --lease-minutes 60"),
    "node spawn": _page("floati node spawn - create one numbered role instance", "floati node spawn --root ROOT --as ACTOR --profile PROFILE [--ordinal N]", "Allocate the first ordinal free in the live registry and provision the derived seat before emitting its boot prompt.", "    --ordinal refuses a live collision; automatic allocation is serialized by the registry append. No model call occurs.", "    floati node spawn --root ~/fleet --as architect-a --profile sre"),
    "node retire": _page("floati node retire - retire one node or numbered instance", "floati node retire --root ROOT (--node NODE | --instance PROFILE-N) [--as ACTOR --drain]", "Existing --node retirement retains its workspace; numbered --instance retirement drains work and mail, proves Git reachability, and receipts removal.", "    --instance requires --as and --drain. Records and receipts outlive a removed numbered workspace.", "    floati node retire --root ~/fleet --instance sre-2 --as architect-a --drain"),
    "node switch": _page("floati node switch - switch provider assignment", "floati node switch --root ROOT --node NODE --harness HARNESS --model MODEL", "Preview and atomically commit the replacement registry row and provider receipt.", "    No model call, fallback, or credential operation occurs.", "    floati node switch --root ~/fleet --node builder-a --harness Cursor --model gpt-5.6"),
    "node role": _page("floati node role - assign a shipped role", "floati node role --root ROOT --node NODE --template ROLE --answer KEY=VALUE [...]", "Answer only declared template questions and preview the exact typed role record.", "    Answers must exactly match the selected template questions.", "    floati node role --root ~/fleet --node builder-a --template builder --answer repo=floati --answer never_touch=foreign-bus --answer reports_to=architect-a"),
    "node boot": _page("floati node boot - project live boot context", "floati node boot --root ROOT --node NODE --declared-roots FILE --managed-executable COMMAND --profile PROFILE [--json]", "Re-read live registry, role, topology, wake, and managed-bus evidence for one boot projection.", "    This command prints a projection; it does not launch a harness.", "    floati node boot --root ~/fleet --node builder-a --declared-roots ~/declared.json --managed-executable /usr/local/bin/floati-fleet --profile builder-a --json"),
    "node teardown": _page("floati node teardown - project the retention ritual", "floati node teardown --root ROOT --node NODE --declared-roots FILE --managed-executable COMMAND --profile PROFILE [--json]", "Re-read live evidence and project the ordered state-preserving teardown ritual.", "    Projection does not retire a node, close a lease, or delete a workspace.", "    floati node teardown --root ~/fleet --node builder-a --declared-roots ~/declared.json --managed-executable /usr/local/bin/floati-fleet --profile builder-a --json"),
    "node explain": _page("floati node explain - explain one live node", "floati node explain --root ROOT --node NODE --declared-roots FILE --managed-executable COMMAND --profile PROFILE [--json]", "Explain one node from a fresh boot projection and typed role provenance.", "    No state-file content, model, network, or foreign root is read.", "    floati node explain --root ~/fleet --node builder-a --declared-roots ~/declared.json --managed-executable /usr/local/bin/floati-fleet --profile builder-a --json"),
    "node state-flush": _page("floati node state-flush - receipt one state flush", "floati node state-flush --root ROOT --node NODE [--prior-mtime-ns NS]", "Observe canonical STATE.md metadata and return a content-free flush receipt.", "    The file is never parsed or copied; an optional prior mtime must be exceeded.", "    floati node state-flush --root ~/fleet --node builder-a"),
    "role": _page("floati role - inspect shipped role templates", "floati role {list|show} [OPTIONS]", "Read the typed shipped role library without model or network access.", "    Subcommands: list, show.", "    floati role list --root ~/fleet"),
    "role list": _page("floati role list - list shipped roles", "floati role list --root ROOT", "List the shipped typed role names.", "    --root ROOT   Existing explicit fleet root.", "    floati role list --root ~/fleet"),
    "role show": _page("floati role show - show one shipped role", "floati role show --root ROOT ROLE", "Show one immutable typed template and its digest.", "    ROLE   Exact shipped role name.", "    floati role show --root ~/fleet architect"),
    "quota": _page("floati quota - inspect or collect cited local quota testimony", "floati quota {collect|show}", "Operate only the six ruled local quota adapters.", "    Subcommands are collect and show; neither discovers credentials, settings, roots, or network surfaces.", "    floati quota show --root ~/fleet --provider openai_codex"),
    "quota collect": _page("floati quota collect - collect one local quota receipt", "floati quota collect --root ROOT --provider PROVIDER --observed-at ISO --idempotency-key KEY [--executable PATH]", "Append one citation-bound quota receipt from a ruled local intake.", "    Claude and Gemini read bounded standard input; Codex requires an explicit local app-server executable; honest UNKNOWN cells read no provider surface.", "    floati quota collect --root ~/fleet --provider openai_codex --observed-at 2026-08-29T12:00:00Z --idempotency-key quota-1 --executable /opt/homebrew/bin/codex"),
    "quota show": _page("floati quota show - inspect one provider quota receipt", "floati quota show --root ROOT --provider PROVIDER", "Read the latest durable quota receipt for one ruled provider.", "    This command is read-only and returns typed no_result when no receipt exists.", "    floati quota show --root ~/fleet --provider cursor_individual"),
    "context": _page("floati context - inspect context evidence and manage Tide signals", "floati context {status|turnover|policy|reading}", "Inspect cited harness evidence, project the read-only turnover ritual, or manage optional Tide policy and testimony.", "    Subcommands: status, turnover, policy, reading. Status and turnover are read-only; policy and reading use durable Tide ledgers.", "    floati context status --root ~/fleet --as builder-a --json"),
    "context status": _page("floati context status - report harness evidence", "floati context status --root ROOT --as NODE [--json]", "Report the selected node's citation-bound external context evidence.", "    --root ROOT   Existing explicit fleet root.\n    --as NODE     Exact active node whose recorded harness is projected.\n    --json        Emit the compact artifact twin.\n    This physically read-only projection never invents a measurement.", "    floati context status --root ~/fleet --as builder-a --json"),
    "context turnover": _page("floati context turnover - project the turnover ritual", "floati context turnover --root ROOT --as NODE [--json]", "Project teardown, metadata-only state flush, and successor boot in order.", "    --root ROOT   Existing explicit fleet root.\n    --as NODE     Exact active node whose live role provenance is projected.\n    --json        Emit the compact artifact twin.\n    The recipe prints command argv and performs no step.", "    floati context turnover --root ~/fleet --as builder-a --json"),
    "context policy": _page("floati context policy - manage Tide context policy", "floati context policy {set|show|clear}", "Set, inspect, or clear one optional node-bound Tide policy.", "    Subcommands: set, show, clear. Mutations require an explicit idempotency key.", "    floati context policy show --root ~/fleet --node builder-a --json"),
    "context policy set": _page("floati context policy set - set one Tide policy", "floati context policy set --root ROOT --node NODE --metric METRIC --threshold THRESHOLD --action recommend|direct --idempotency-key KEY [--json]", "Append one exact node-bound policy to the durable Tide policy ledger.", "    --root ROOT               Existing explicit fleet root.\n    --node NODE               Exact active node.\n    --metric METRIC           Ruled Tide metric.\n    --threshold THRESHOLD     Metric threshold text.\n    --action recommend|direct Ruled action.\n    --idempotency-key KEY     Stable replay key.\n    --json                    Emit the compact artifact twin.", "    floati context policy set --root ~/fleet --node builder-a --metric context_fraction --threshold 20% --action recommend --idempotency-key tide-1 --json"),
    "context policy show": _page("floati context policy show - show one Tide policy", "floati context policy show --root ROOT --node NODE [--json]", "Read the active node-bound Tide policy or return its typed absence.", "    --root ROOT   Existing explicit fleet root.\n    --node NODE   Exact active node.\n    --json        Emit the compact artifact twin.", "    floati context policy show --root ~/fleet --node builder-a --json"),
    "context policy clear": _page("floati context policy clear - clear one Tide policy", "floati context policy clear --root ROOT --node NODE --idempotency-key KEY [--json]", "Append an exact clearing record for one active node-bound Tide policy.", "    --root ROOT               Existing explicit fleet root.\n    --node NODE               Exact active node.\n    --idempotency-key KEY     Stable replay key.\n    --json                    Emit the compact artifact twin.", "    floati context policy clear --root ~/fleet --node builder-a --idempotency-key tide-clear-1 --json"),
    "context reading": _page("floati context reading - record seated context testimony", "floati context reading {record}", "Manage bounded Class-B context testimony from a seated node.", "    Subcommands: record. A reading records testimony; it does not create an external measurement.", "    floati context reading record --root ~/fleet --as builder-a --metric self_reported_context_fraction --value 42% --command /context --idempotency-key reading-1 --json"),
    "context reading record": _page("floati context reading record - append context testimony", "floati context reading record --root ROOT --as NODE --metric METRIC --value VALUE --command /context|/status|/usage|/cost --idempotency-key KEY [--json]", "Append one exact seated-node testimony row to the durable Tide testimony ledger.", "    --root ROOT               Existing explicit fleet root.\n    --as NODE                 Exact seated node.\n    --metric METRIC           Ruled Tide metric.\n    --value VALUE             Testified value text.\n    --command COMMAND         Exact supported slash-command source.\n    --idempotency-key KEY     Stable replay key.\n    --json                    Emit the compact artifact twin.", "    floati context reading record --root ~/fleet --as builder-a --metric self_reported_context_fraction --value 42% --command /context --idempotency-key reading-1 --json"),
    "chart": _page("floati chart - multi-bus Harbor Chart", "floati chart --declared-roots FILE [--live] [--json]", "Read only explicitly declared roots and validated ledgers; never discover roots. Use the live Harbor Map only when explicitly requested.", "    --declared-roots FILE   Required absolute declarations file.\n    --live                  Run the interactive Harbor Map in a TTY; otherwise render its text twin.\n    --json                  Emit only the compact artifact twin.", "    floati chart --declared-roots ~/declared.json --live"),
    "survey": _page("floati survey - read-only foreign-bus survey", "floati survey --declared-roots FILE [--search-path PATH] [--hooks FILE] [--targets FILE] [--json]", "Survey one explicit bounded request without writing, draining, acknowledging, registering, or locking a foreign bus.", "    --search-path PATH   Repeatable explicit directory.\n    --hooks FILE         Optional explicit hook JSON.\n    --targets FILE       Repeatable explicit target JSON.", "    floati survey --declared-roots ~/declared.json --search-path ~ --json"),
    "confluence": _page("floati confluence - the read seam for a consuming observer app", "floati confluence {grant|revoke|status|bundle} [OPTIONS]", "Grant, sever, list, or exercise one explicit per-root read grant; materialize the receipts-read bundle under the grant it was produced under.", "    One grant is one root and one consumer identity. No discovery, no watcher, no network, no mutation API.", "    floati confluence grant --root ~/fleet --consumer puddle --idempotency-key c-1"),
    "confluence grant": _page("floati confluence grant - record one explicit read grant", "floati confluence grant --root ROOT --consumer IDENTITY --idempotency-key KEY", "Record one receipted per-root read grant for one consumer identity.", "    The grant names the exact root; never a home scan, never a glob.", "    floati confluence grant --root ~/fleet --consumer puddle --idempotency-key c-1"),
    "confluence revoke": _page("floati confluence revoke - sever one explicit read grant", "floati confluence revoke --root ROOT --consumer IDENTITY --idempotency-key KEY", "Sever the active grant for one consumer; reads refuse from the next exercise.", "    Revoking a consumer without an active grant is a typed refusal.", "    floati confluence revoke --root ~/fleet --consumer puddle --idempotency-key c-2"),
    "confluence adopt": _page("floati confluence adopt - adopt one session into managed mode", "floati confluence adopt --root ROOT --consumer IDENTITY --session SESSION --manager NODE --authority-subject SUBJECT --authority-epoch N --authority-expires-at TIMESTAMP", "Record one MANAGED-mode session adoption under the consumer's grant and the manager's exact active authority lease.", "    Two trust gates apply and neither substitutes for the other: the read-seam grant and the L1 authority binding.", "    floati confluence adopt --root ~/fleet --consumer puddle --session sess-1 --manager manager-a --authority-subject subj-1 --authority-epoch 1 --authority-expires-at 2026-08-31T00:00:00.000Z"),
    "confluence release": _page("floati confluence release - release one adopted session", "floati confluence release --root ROOT --consumer IDENTITY --session SESSION --manager NODE --authority-epoch N", "Record one release binding the exact active adoption, manager, and lease epoch.", "    Both trust gates apply here exactly as on adopt.", "    floati confluence release --root ~/fleet --consumer puddle --session sess-1 --manager manager-a --authority-epoch 1"),
    "confluence status": _page("floati confluence status - list recorded read grants", "floati confluence status --root ROOT", "List every recorded grant and revocation for one root, in ledger order.", "    The listing is physically read-only and names each grant it shows.", "    floati confluence status --root ~/fleet"),
    "confluence bundle": _page("floati confluence bundle - materialize the receipts-read bundle", "floati confluence bundle --root ROOT --consumer IDENTITY --out PATH", "Materialize the grant-stamped receipts-read bundle deterministically to one explicit absolute path.", "    Reads by an ungranted consumer refuse naming the grant act. The only write is the requested output path.", "    floati confluence bundle --root ~/fleet --consumer puddle --out ~/bundle.json"),
    "wake": _page("floati wake - control exact wake coordinates", "floati wake {arm|pause|resume|status|daemon} [OPTIONS]", "Arm one exact acting session, control one exact session marker, or manage one consented local wake daemon coordinate.", "    Global and wildcard selectors do not exist. Use a subcommand --help for its exact contract.\n    The installed Codex Stop hook runs scripts/floati-codex-wait --root ROOT; node, workspace, and acting session come only from its validated hook payload.", "    floati wake arm --root ~/fleet --as builder-a --session codex-session --workspace /repo --idempotency-key arm-1"),
    "wake arm": _page("floati wake arm - arm one exact acting session", "floati wake arm --root ROOT --as NODE --session SESSION --workspace PATH --idempotency-key KEY", "Append an initial arm or predecessor-bound takeover for one consented workspace binding.", "    The actor must own the exact mapped workspace. Re-arming replaces only the prior session authority and leaves hook registration unchanged.", "    floati wake arm --root ~/fleet --as builder-a --session codex-session --workspace /repo --idempotency-key arm-1"),
    "wake pause": _page("floati wake pause - pause one exact session", "floati wake pause --root ROOT --as NODE --session SESSION", "Record a pause receipt and commit one exact session marker.", "    Paused is a recorded state, not absence or deafness.\n    --idempotency-key KEY carries your replay key; when absent the CLI mints one and echoes it in the artifact.", "    floati wake pause --root ~/fleet --as builder-a --session 01a0..."),
    "wake resume": _page("floati wake resume - resume one exact session", "floati wake resume --root ROOT --as NODE --session SESSION", "Record the symmetric resume request and remove only the exact pause marker.", "    Hook registration and every other session remain unchanged.\n    --idempotency-key KEY carries your replay key; when absent the CLI mints one and echoes it in the artifact.", "    floati wake resume --root ~/fleet --as builder-a --session 01a0..."),
    "wake status": _page("floati wake status - inspect one exact session", "floati wake status --root ROOT --as NODE --session SESSION", "Report active or paused and name the running session cache and harness trust gate as unknown.", "    Status is physically read-only and never infers deafness from a pause.", "    floati wake status --root ~/fleet --as builder-a --session 01a0..."),
    "wake daemon": _page("floati wake daemon - manage one local wake daemon", "floati wake daemon {consent|bind|install|start|status|stop|remove|revoke} [OPTIONS]", "Manage one exact node and harness coordinate with explicit consent and digest-bound local evidence.", "    Public subcommands do not accept arbitrary commands, fallback roots, or global selectors.", "    floati wake daemon status --root ~/fleet --as builder-a --harness cursor"),
    "wake daemon consent": _page("floati wake daemon consent - record exact activation consent", "floati wake daemon consent --root ROOT --as NODE --harness codex|cursor|grok-build|zcode --min-poll-seconds N --max-poll-seconds N --max-backoff-seconds N --activation-epoch N", "Record bounded polling consent for one exact adapter contract.", "    Consent records evidence only; it does not install or invoke launchctl.", "    floati wake daemon consent --root ~/fleet --as builder-a --harness cursor --min-poll-seconds 1 --max-poll-seconds 30 --max-backoff-seconds 120 --activation-epoch 1"),
    "wake daemon bind": _page("floati wake daemon bind - bind one exact session", "floati wake daemon bind --root ROOT --as NODE --harness cursor|grok-build --session SESSION --workspace PATH --executable PATH --binding-epoch N [--yes]", "Record one exact session, workspace, and executable digest.", "    --yes  Consent to the turn-costing resume probe without the interactive ask.\n    Codex bindings are accepted only from the trusted waiter and are refused here.", "    floati wake daemon bind --root ~/fleet --as builder-a --harness cursor --session SESSION --workspace /repo --executable /opt/homebrew/bin/cursor-agent --binding-epoch 1"),
    "wake daemon install": _page("floati wake daemon install - install the exact LaunchAgent", "floati wake daemon install --root ROOT --as NODE --harness codex|cursor|grok-build|zcode", "Install deterministic digest-bound plist bytes without starting them.", "    Installation requires active consent and an exact adapter binding; it does not invoke launchctl.", "    floati wake daemon install --root ~/fleet --as builder-a --harness cursor"),
    "wake daemon start": _page("floati wake daemon start - start the exact LaunchAgent", "floati wake daemon start --root ROOT --as NODE --harness codex|cursor|grok-build|zcode", "Bootstrap and kickstart only the deterministic user-domain LaunchAgent.", "    A missing or changed plist is a typed refusal.", "    floati wake daemon start --root ~/fleet --as builder-a --harness cursor"),
    "wake daemon status": _page("floati wake daemon status - inspect one daemon coordinate", "floati wake daemon status --root ROOT --as NODE --harness codex|cursor|grok-build|zcode", "Report inactive before consent and otherwise inspect only the exact installed supervisor coordinate.", "    Inactive status is physically read-only and does not create daemon state.", "    floati wake daemon status --root ~/fleet --as builder-a --harness cursor"),
    "wake daemon stop": _page("floati wake daemon stop - stop the exact LaunchAgent", "floati wake daemon stop --root ROOT --as NODE --harness codex|cursor|grok-build|zcode", "Request bootout and prove process absence for one exact user-domain label.", "    Unproven process absence is reported as unknown.", "    floati wake daemon stop --root ~/fleet --as builder-a --harness cursor"),
    "wake daemon remove": _page("floati wake daemon remove - remove the exact LaunchAgent", "floati wake daemon remove --root ROOT --as NODE --harness codex|cursor|grok-build|zcode", "Quarantine and remove only matching deterministic plist bytes.", "    Removal refuses symlinks, inode changes, and digest drift.", "    floati wake daemon remove --root ~/fleet --as builder-a --harness cursor"),
    "wake daemon revoke": _page("floati wake daemon revoke - revoke exact daemon consent", "floati wake daemon revoke --root ROOT --as NODE --harness codex|cursor|grok-build|zcode", "Stop and remove matching supervisor bytes, then append exact consent revocation.", "    If process absence cannot be proved, final state remains unknown.", "    floati wake daemon revoke --root ~/fleet --as builder-a --harness cursor"),
    "register": _page("floati register - register this node", "floati register --root ROOT NODE --harness HARNESS [--create-workspace]", "Append one active node registration. A node registers only itself.", "    --root ROOT         Explicit direct-home fleet root.\n    NODE                Bounded node identifier.\n    --harness HARNESS   Harness role recorded on disk.\n    --create-workspace  Also create the node's workspace layout during registration.", "    floati register --root ~/fleet builder-a --harness Codex"),
    "retire": _page("floati retire - retire this node's registry row", "floati retire --root ROOT NODE", "Append one retirement row for the calling node, under the same lock register uses. Self-retirement only; the registered role carries forward and the ledger stays append-only. A retired node leaves the active roster; its history remains readable.", "    --root ROOT   Explicit direct-home fleet root.\n    NODE          The node retiring itself. Retiring another node (--as, --actor) is refused.", "    floati retire --root ~/fleet builder-a"),
    "send": _page("floati send - append a Git notification", "floati send --root ROOT --from NODE --to NODE --repo REPO --sha SHA --doc PATH --note TEXT [--claim PATH] [--reply-to ID] [--idempotency-key KEY]", "Send a Git-authoritative notification, optionally with one typed delivery claim. Delivery and acknowledgment remain separate receipts.", "    --claim PATH           strict JSON delivery-claim document; floati binds the new envelope id.\n    --reply-to ID          Existing reversed-party message binding.\n    --idempotency-key KEY  Stable replay key; the effective key is echoed.\n    All routing and Git fields are required.", "    floati send --root ~/fleet --from a --to b --repo floati --sha <sha> --doc docs/evidence/checkpoint.md --note checkpoint --claim ~/claim.json"),
    "verify": _page("floati verify - reproduce a typed delivery claim", "floati verify --root ROOT --as NODE --claim ID [--json]", "Reproduce one claimed test bank and artifact set in a fresh exact-SHA local worktree, then append a typed verification receipt.", "    --root ROOT   Explicit fleet root whose ledger holds the claim.\n    --as NODE     Registered verifier identity.\n    --claim ID    Exact delivery-claim id.\n    --json        Emit the stable JSON artifact.\n    Floati never fetches; absent or unbanked SHAs refuse with a human remedy.", "    floati verify --root ~/fleet --as gate-a --claim delivery-claim-<id> --json"),
    "inbox": _page("floati inbox - drain pending mail", "floati inbox --root ROOT --as NODE (--session SESSION | --peek)", "Present pending notifications and, by default, acknowledge exactly the returned batch in the same guarded operation. --peek is the explicit non-acknowledging variant.", "    --root ROOT       Explicit fleet root.\n    --as NODE         Exact registered recipient.\n    --session SESSION Exact acting harness session for the default acknowledgment.\n    --peek            Append delivery evidence without acknowledgment; cannot combine with --session.", "    floati inbox --root ~/fleet --as builder-a --session codex-session"),
    "ack": _page("floati ack - acknowledge presented messages", "floati ack --root ROOT --as NODE --session SESSION --id MESSAGE [--id MESSAGE ...]", "Append one actor-bound acknowledgment receipt for an exact non-empty message batch. Acknowledgment does not claim action or completion.", "    --root ROOT       Explicit fleet root.\n    --as NODE         Exact recipient.\n    --session SESSION Exact acting harness session.\n    --id MESSAGE      Previously presented message identifier; repeat for a batch.", "    floati ack --root ~/fleet --as builder-a --session codex-session --id msg-1 --id msg-2"),
    "sent": _page("floati sent - project sender receipt state", "floati sent --root ROOT --as NODE", "Read the event, delivery, and acknowledgment ledgers to project each sent message without mutating any plane.", "    --root ROOT   Explicit fleet root.\n    --as NODE     Exact registered sender.\n    States distinguish sent, delivered_unacknowledged, and acknowledged; measured ages and latencies remain null until their receipts exist.", "    floati sent --root ~/fleet --as architect-a"),
    "grant": _page("floati grant - append exact work authority", "floati grant --root ROOT --as GRANTOR --holder NODE --subject SUBJECT --epoch N", "Grant one exact holder, subject, and epoch coordinate when GRANTOR has an active architect role record.", "    --root ROOT       Existing explicit fleet root.\n    --as GRANTOR      Active node with the architect role template.\n    --holder NODE     Exact active authority holder.\n    --subject SUBJECT Exact authority subject; wildcards do not exist.\n    --epoch N         Exact positive authority epoch.\n    Exact active-coordinate replay is idempotent; a higher epoch supersedes the prior coordinate.", "    floati grant --root ~/fleet --as architect-a --holder builder-a --subject work-claims --epoch 1"),
    "grant revoke": _page("floati grant revoke - revoke exact work authority", "floati grant revoke --root ROOT --as GRANTOR --holder NODE --subject SUBJECT --epoch N", "Revoke one exact authority coordinate under the same architect-role gate as grant.", "    --root ROOT       Existing explicit fleet root.\n    --as GRANTOR      Active node with the architect role template.\n    --holder NODE     Exact authority holder.\n    --subject SUBJECT Exact authority subject.\n    --epoch N         Exact current authority epoch.\n    Exact repeated revocation returns the durable revoking record. For credential aliases, revocation blocks new delivery but cannot retract a value already held by a running process.", "    floati grant revoke --root ~/fleet --as architect-a --holder builder-a --subject work-claims --epoch 1"),
    "log": _page("floati log - read mail or replay orchestration evidence", "floati log --root ROOT [--replay [--speed X] [--plain]]", "Read canonical ledgers. Replay renders receipt-derived orchestration events in deterministic order.", "    --root ROOT   Explicit fleet root.\n    --replay      Render claims, turns, degradations, denials, and completions.\n    --speed X     Interactive playback speed from 0.1 through 100; default 1.\n    --plain       Emit one faithful append-only timeline without sleeping.", "    floati log --root ~/fleet\n    floati log --root ~/fleet --replay --speed 4\n    floati log --root ~/fleet --replay --plain"),
    "status": _page("floati status - summarize the fleet", "floati status --root ROOT [--destination PATH] [--json]", "Emit one compact whole-fleet snapshot with three separate plane states, work counts, and receipt counts. --json selects the documented stable version-zero read contract.", "    --root ROOT   Explicit fleet root.\n    --destination PATH   Installed bundle for the installer-shadow observation; defaults to the FLOATI_INSTALL_DESTINATION environment variable when unset.\n    --json        Declare machine consumption of the version-zero contract.", "    floati status --root ~/fleet\n    floati status --root ~/fleet --json"),
    "snapshot": _page("floati snapshot - build one consented maintainer support bundle", "floati snapshot --root ROOT --out PATH [--lines N] [--yes]", "Collect one identity-scrubbed diagnostic bundle that an operator can hand to a maintainer.", "    --root ROOT   Exact explicit fleet root.\n    --out PATH   Operator-selected tarball path outside .floati-snapshots.\n    --lines N    Last lines retained from every derived ledger plane; default 240.\n    --yes        Print the same disclosure and skip only the interactive question.\n    Without --yes, a non-interactive terminal refuses instead of blocking.", "    floati snapshot --root ~/fleet --out ~/floati-support.tar.gz"),
    "effects": _page("floati effects - list projected effect status", "floati effects --root ROOT [--run RUN_ID] [--attempt ATTEMPT_ID]", "Read the deterministic version-one effect projection without creating files or locks.", "    --root ROOT           Existing explicit fleet root.\n    --run RUN_ID          Optional exact run UUIDv7 identifier.\n    --attempt ATTEMPT_ID  Optional exact attempt UUIDv7 identifier.", "    floati effects --root ~/fleet\n    floati effects --root ~/fleet --run run-... --attempt attempt-..."),
    "effect": _page("floati effect - inspect or operate one effect", "floati effect {show|reconcile|compensate} [OPTIONS]", "Use one typed operation identifier for read-only inspection, frozen-adapter reconciliation, or fail-closed compensation planning.", "    Subcommands: show, reconcile, compensate. Use a subcommand --help for its exact contract.\n    No raw record, adapter, result, credential, request body, or authority input exists.", "    floati effect show --root ~/fleet --operation effect-op-..."),
    "effect show": _page("floati effect show - inspect one exact effect", "floati effect show --root ROOT --operation OPERATION_ID", "Read one exact projected effect operation without creating files or locks.", "    --root ROOT                Existing explicit fleet root.\n    --operation OPERATION_ID  Exact effect operation UUIDv7 identifier.", "    floati effect show --root ~/fleet --operation effect-op-..."),
    "effect reconcile": _page("floati effect reconcile - reconcile one effect", "floati effect reconcile --root ROOT --operation OPERATION_ID", "Run only the reconciliation adapter frozen in durable effect intent, using the canonical repository policy at ROOT/FLOATI.toml.", "    --root ROOT                Existing explicit fleet root.\n    --operation OPERATION_ID  Exact effect operation UUIDv7 identifier.\n    No adapter or result override exists.", "    floati effect reconcile --root ~/fleet --operation effect-op-..."),
    "effect compensate": _page("floati effect compensate - request compensation planning", "floati effect compensate --root ROOT --operation OPERATION_ID (--preview | --confirm PLAN_DIGEST)", "Fail closed because this CLI has no durable compensation action specification from which to construct or recover the exact plan. Preview and confirmation report typed unavailability without writing.", "    --root ROOT                Existing explicit fleet root.\n    --operation OPERATION_ID  Exact effect operation UUIDv7 identifier.\n    --preview                  Request a physically read-only preview.\n    --confirm PLAN_DIGEST     Name one lowercase SHA-256 plan digest.\n    Exactly one mode is required; neither mode accepts plan fields or authority.", "    floati effect compensate --root ~/fleet --operation effect-op-... --preview\n    floati effect compensate --root ~/fleet --operation effect-op-... --confirm <digest>"),
    "threads": _page("floati threads - list registered thread observations", "floati threads --root ROOT", "Read registered threads only through a pull-only projection; provider status is not task state.", "    --root ROOT   Existing explicit fleet root. No provider inventory or mutation is performed.", "    floati threads --root ~/fleet"),
    "thread": _page("floati thread - operate one registered thread attachment", "floati thread {attach|observe|detach|show} [OPTIONS]", "Operate registered threads only through a pull-only source; provider status is not task state.", "    Subcommands: attach, observe, detach, show. No raw provider status, content, prompt, or task-state input exists.", "    floati thread show --root ~/fleet --attachment thread-attachment-..."),
    "thread attach": _page("floati thread attach - register one explicit provider thread", "floati thread attach --root ROOT --as NODE --thread THREAD_ID --work-item WORK_ID [--run RUN_ID --attempt ATTEMPT_ID]", "Register one exact Codex task coordinate without sampling provider state; registered threads only are observable later.", "    Supply a work item alone, or the exact run, work item, and attempt. The actor must be registered.", "    floati thread attach --root ~/fleet --as observer --thread <uuid> --work-item work-..."),
    "thread observe": _page("floati thread observe - pull one registered provider status", "floati thread observe --root ROOT --attachment ATTACHMENT_ID --codex-executable PATH", "Perform one bounded pull-only read. Provider status is not task state.", "    --codex-executable PATH  Explicit canonical local Codex executable.\n    No status, timestamp, flag, title, text, or raw JSON option exists.", "    floati thread observe --root ~/fleet --attachment thread-attachment-... --codex-executable /opt/homebrew/bin/codex"),
    "thread detach": _page("floati thread detach - stop future observations", "floati thread detach --root ROOT --as NODE --attachment ATTACHMENT_ID", "Append one durable detachment for a registered thread; provider state is not mutated.", "    --as NODE must name the exact registered detaching actor.", "    floati thread detach --root ~/fleet --as observer --attachment thread-attachment-..."),
    "thread show": _page("floati thread show - inspect one exact attachment", "floati thread show --root ROOT --attachment ATTACHMENT_ID", "Read one registered thread attachment without provider access or writes.", "    The exact attachment view may reveal its registered provider coordinate.", "    floati thread show --root ~/fleet --attachment thread-attachment-..."),
    "graph": _page("floati graph - render the Harbor Chart", "floati graph --root ROOT [--json]", "Render a deterministic fleet map from durable ledgers only. Human output composes frozen topology with counts-only traffic; --json emits frozen topology v0.", "    --root ROOT   Explicit fleet root.\n    --json        Emit the frozen version-zero topology artifact.", "    floati graph --root ~/fleet\n    floati graph --root ~/fleet --json"),
    "plan": _page("floati plan - explain read-only plan admission", "floati plan [--root ROOT] --plan PLAN --policy POLICY --explain [--json]", "Read-only plan admission reports admitted, refused, or needs_operator from hard limits.", "    --root ROOT       Explicit fleet root.\n    --plan PLAN       Explicit absolute plan path.\n    --policy POLICY   Explicit absolute FLOATI.toml path.\n    --explain         Required read-only explanation.\n    --json            Declare machine consumption of the version-zero contract.", "    floati plan --plan ~/plan.json --policy ~/FLOATI.toml --explain --json"),
    "doctor": _page("floati doctor - diagnose root and bundle integrity", "floati doctor --root ROOT --source SOURCE [--ref REF] [--gateway-config PATH] [--profile PROFILE] [--no-sandbox] [--probe] [--probe-budget SECONDS] [--destination PATH] [--codex-hooks PATH] [--codex-config PATH]", "Run physically read-only typed checks for root, registry, manifest, currency, symlink identity, the sole consumption coordinate, sandbox write coordinates, and an explicitly supplied local gateway config. Sandbox checks run by default.", "    --root ROOT       Explicit fleet direct home.\n    --source SOURCE   Explicit Floati source checkout.\n    --ref REF         Named deployment currency ref; default origin/main.\n    --gateway-config PATH  Optional local stdio gateway v0 config; no discovery.\n    --profile PROFILE      Optional ruled profile (bus-only, orchestration), never inferred; bus-only expects live directories to be absent.\n    --no-sandbox          Skip the default sandbox write-set checks. There is no enabling flag because checks are on by default.\n    --probe              Send a loopback envelope to every registered node and verify each drains it within the budget (appends probe mail; per-node PASS/DEAF).\n    --probe-budget SECONDS  Probe drain budget in seconds per node; default 60.\n    --destination PATH   Installed bundle for the installer-shadow observation; defaults to the FLOATI_INSTALL_DESTINATION environment variable when unset.\n    --codex-hooks PATH   Exact Codex hooks.json path for per-hook trust measurement.\n    --codex-config PATH  Exact Codex config.toml path containing hook trust state.\n    The installer-shadow check reads PATH as supplied; a PATH that omits the install scripts directory yields unknown, naming the blocked entry - a partial scan is never reported as no-shadowing.\n    Remediation is printed only when its currency prerequisites are established.", "    floati doctor --root ~/fleet --source /repo/floati --ref origin/lane/hm0 --gateway-config ~/gateway.json"),
    "watch": _page("floati watch - poll for fleet deltas", "floati watch --root ROOT [--destination PATH] [--interval SECONDS] [--iterations COUNT]", "Stream one artifact for the initial observation and each changed observation.", "    --root ROOT   Explicit fleet root.\n    --destination PATH   Installed bundle for the installer-shadow observation; defaults to the FLOATI_INSTALL_DESTINATION environment variable when unset.\n    --interval SECONDS   Poll interval from 0.05 through 60; default 0.25.\n    --iterations COUNT   Bounded poll count; default continues until interrupted.", "    floati watch --root ~/fleet --interval 0.25 --iterations 20"),
    "receipts": _page("floati receipts - inspect node receipt history", "floati receipts NODE --root ROOT", "Read delivery, acknowledgment, and denial histories as distinct evidence.", "    NODE          Exact registered node.\n    --root ROOT   Explicit fleet root.", "    floati receipts builder-a --root ~/fleet"),
    "supervise": _page("floati supervise - report fleet health", "floati supervise --root ROOT", "Run a physically read-only report of liveness, authority, mutex, inbox depth, and stale leases.", "    --root ROOT   Explicit fleet root. No action option exists.", "    floati supervise --root ~/fleet"),
    "presence": _page("floati presence - self-report or inspect node liveness", "floati presence {report|show} [OPTIONS]", "Record only the acting node's own bounded liveness report, or inspect what every active node last reported.", "    Subcommands: report, show. Expiry means no report since the named time; it never means down.", "    floati presence show --root ~/fleet"),
    "presence report": _page("floati presence report - record this node's own liveness", "floati presence report --root ROOT --as NODE --ttl-seconds N", "Append one self-report for the exact active acting node. There is no target-node argument.", "    --root ROOT          Existing explicit fleet root.\n    --as NODE            Exact active node reporting about itself.\n    --ttl-seconds N      Explicit report TTL from 1 through 86400 seconds.", "    floati presence report --root ~/fleet --as builder-a --ttl-seconds 120"),
    "presence show": _page("floati presence show - inspect node self-reports", "floati presence show --root ROOT", "List every active node's last reported time, TTL, expiry, and honest report state without inferring that any node is down.", "    --root ROOT   Existing explicit fleet root. This operation is read-only.", "    floati presence show --root ~/fleet"),
    "board": _page("floati board - open the TUI harbor board", "floati board (--root ROOT --session SESSION | --demo) [--no-animation]", "Render the keyboard-first fleet board. Live acknowledgment is actor-bound. Dumb terminals receive a distinguishable plain dump.", "    --root ROOT       Explicit fleet root.\n    --session SESSION Exact acting harness session for live acknowledgment.\n    --demo            Use a throwaway synthetic fleet.\n    --no-animation    Emit one final frame without terminal control.", "    floati board --root ~/fleet --session codex-session\n    floati board --demo --no-animation"),
    "orchestrate": _page("floati orchestrate - seed and run a worker fleet", "floati orchestrate --root ROOT --plan PLAN --adapter codex --deadline SECONDS [--no-animation]", "Seed a bounded work DAG, launch at least three workers, stream the receipt-derived board, and emit one final artifact.", "    --root ROOT       Explicit prepared fleet root with registrations and authority.\n    --plan PLAN       Absolute version-zero orchestration plan path.\n    --adapter codex   Exact governed live-worker adapter.\n    --deadline SECONDS  Overall deadline from 0.1 through 3600.\n    --no-animation    Stream distinguishable plain text frames.", "    floati orchestrate --root ~/fleet --plan ~/plan.json --adapter codex --deadline 120"),
    "work": _page("floati work - operate the orchestration log", "floati work {add|claim|complete|show} [OPTIONS]", "Operate work items independently from mail.", "    Subcommands: add, claim, complete, show. Use a subcommand --help for its exact contract.", "    floati work show --root ~/fleet"),
    "work add": _page("floati work add - append a work item", "floati work add --root ROOT --title TEXT [--owner NODE] [--needs WORK] [--workspace] [--repo REPO --sha SHA --doc PATH]", "Append one open work item with optional dependency edges and Git artifact binding.", "    Artifact options are all-or-none. --owner may be omitted only in a solo root.\n    --needs WORK  Require one existing work item; repeat for multiple dependencies.\n    --workspace   Add the ruled absolute workspace under /private~/floati-work/<work-id>/; the worker creates it.", "    floati work add --root ~/my-sessions --title 'record this session'\n    floati work add --root ~/fleet --title 'build board' --owner builder-a --needs work-..."),
    "work claim": _page("floati work claim - claim with authority", "floati work claim --root ROOT --id WORK [--as NODE --authority-subject SUBJECT --authority-epoch EPOCH] [--now TIME]", "Append a claim only when the exact authority holder and epoch are active. Solo roots may resolve the one configured identity and grant.", "    --as, --authority-subject, and --authority-epoch may be omitted only when solo resolution is unambiguous.\n    --now TIME   Optional UTC RFC3339 observation for deterministic operation.", "    floati work claim --root ~/my-sessions --id work-...\n    floati work claim --root ~/fleet --id work-... --as builder-a --authority-subject build --authority-epoch 1"),
    "work complete": _page("floati work complete - append completion", "floati work complete --root ROOT --id WORK [--as NODE] [--repo REPO --sha SHA --doc PATH] [--now TIME]", "Complete only a work item claimed by the exact actor and retain artifact bindings. Solo roots may resolve the configured actor.", "    Artifact options are all-or-none. --as may be omitted only in a solo root. --now accepts UTC RFC3339.", "    floati work complete --root ~/my-sessions --id work-...\n    floati work complete --root ~/fleet --id work-... --as builder-a"),
    "work show": _page("floati work show - project work state", "floati work show --root ROOT [--id WORK]", "Project all work items or one exact item from append-only records.", "    --id WORK   Optional exact work item identifier.", "    floati work show --root ~/fleet"),
    "intake": _page("floati intake - adopt bounded work-queue sources", "floati intake {scan|adopt|show|preview|dispatch} [OPTIONS]", "Inspect and adopt explicitly selected intake sources through immutable snapshots and the existing work queue.", "    Subcommands: scan, adopt, show, preview, dispatch. Use a subcommand --help for its exact contract.", "    floati intake scan --root ~/fleet --from ~/tasks"),
    "intake scan": _page("floati intake scan - inspect local Markdown intake", "floati intake scan --root ROOT --from DIR", "Read every direct *.md entry in an explicit directory and report eligible or typed-refused verdicts without writing anything.", "    --root ROOT   Existing explicit fleet root; it is required for command binding and is not modified.\n    --from DIR    Explicit local queue directory; scanning is non-recursive.\n    Symlinks, malformed titles, invalid UTF-8, and files over 256 KiB are refused with stable codes.", "    floati intake scan --root ~/fleet --from ~/tasks"),
    "intake show": _page("floati intake show - inspect immutable snapshots", "floati intake show --root ROOT [--id SNAPSHOT_ID]", "Read local intake snapshot records and their payloads, refusing when a payload is missing, altered, or a visible orphan work item has no snapshot row.", "    --root ROOT       Existing explicit fleet root.\n    --id SNAPSHOT_ID  Optional exact immutable snapshot identity.", "    floati intake show --root ~/fleet"),
    "intake adopt": _page("floati intake adopt - adopt one explicit intake source", "floati intake adopt --root ROOT (--source local --from DIR --path RELATIVE | --source github --repo O/R --issue N --gh EXE) [--owner NODE] [--now TIME]", "Write one immutable local Markdown or one-shot GitHub issue snapshot and its work item. This durable verb is not reachable from MCP; only the explicit GitHub shape starts a network-capable subprocess.", f"    --root ROOT       Existing explicit fleet root.\n    --source local --from DIR --path RELATIVE\n                      Read one safe Markdown path relative to an explicit queue.\n    --source github --repo O/R --issue N --gh EXE\n                      Resolve and run one explicit absolute GitHub CLI executable for one named issue.\n    --owner NODE     Optional active work owner; solo roots may omit it.\n    --now TIME       Optional aware UTC RFC3339 retrieval time.\n    Ambient GH_TOKEN or GITHUB_TOKEN may reach only the fixed subprocess environment and is never recorded.\n    {GH_AUTHENTICATION_REMEDY}", "    floati intake adopt --root ~/fleet --source local --from ~/tasks --path good.md --owner builder-a\n    floati intake adopt --root ~/fleet --source github --repo owner/repo --issue 123 --gh /opt/homebrew/bin/gh --owner builder-a"),
    "intake preview": _page("floati intake preview - preview one GitHub mutation", "floati intake preview --root ROOT --snapshot ID --operation OP REQUEST", "Return the exact target, GitHub REST body, digest, risk, and approval requirement without writing or dispatching. This read-only command is MCP-exposed.", "    --operation comment (--body TEXT | --body-file PATH)\n    --operation label_add --label NAME [--label NAME ...]\n    --operation label_remove --label NAME\n    --operation close --reason completed|not_planned\n    --operation pr_link --pr N\n    label_add is sorted and deduplicated; label_remove accepts exactly one label because GitHub removal is not atomic across a set. pr_link uses the fixed comment body 'Linked pull request: #N'.", "    floati intake preview --root ~/fleet --snapshot intake-snapshot-... --operation comment --body 'Acknowledged.'"),
    "intake dispatch": _page("floati intake dispatch - bind a preview to one effect intent", "floati intake dispatch --root ROOT --snapshot ID --operation OP REQUEST --confirm-digest HEX --run-id RUN --item-id WORK --attempt-id ATTEMPT --fence-token TOKEN [APPROVAL]", "Recompute the preview and append through the existing sealed effect controller only when the carried-back digest and live run context match. This outbound command is not reachable from MCP.", "    REQUEST uses the exact operation-specific flags documented by intake preview.\n    --body-file PATH     Operation body read from a file; --body TEXT is the inline alternative.\n    --label NAME         Label for label_add (repeatable, sorted, deduplicated) or label_remove (exactly one).\n    --reason REASON      Close reason: completed or not_planned.\n    --pr N               Pull request number for pr_link.\n    --confirm-digest HEX  Exact recomputed preview digest.\n    --run-id, --item-id, --attempt-id, --fence-token\n                          Existing durable run and attempt context.\n    --approval-request ID --approval-decision ID [--approval-consumption ID]\n                          Existing effect approval evidence when policy requires it.", "    floati intake dispatch --root ~/fleet --snapshot intake-snapshot-... --operation comment --body 'Acknowledged.' --confirm-digest <digest> --run-id run-... --item-id work-... --attempt-id attempt-... --fence-token <token>"),
    "worker": _page("floati worker - run one authority-checked worker", "floati worker run --root ROOT --as NODE --adapter claude|codex|pi", "Claim one owned open work item and record every worker transition as durable evidence.", "    Use worker run for the exact command contract.", "    floati worker run --root ~/fleet --as builder-a --adapter claude"),
    "worker run": _page("floati worker run - run one authority-checked worker", "floati worker run --root ROOT --as NODE --adapter claude|codex|pi [--claude-executable PATH] [--codex-executable PATH] [--pi-executable PATH]", "Claim one owned open work item and record typed degradation without silent fallback.", "    --root ROOT      Explicit fleet root.\n    --as NODE        Exact registered worker node.\n    --adapter claude|codex|pi  Exact governed adapter.\n    --claude-executable PATH   Explicit canonical Claude executable.\n    --codex-executable PATH    Explicit canonical Codex executable.\n    --pi-executable PATH       Explicit canonical pi executable.", "    floati worker run --root ~/fleet --as builder-a --adapter claude --claude-executable /opt/homebrew/bin/claude"),
    "mcp": _page("floati mcp - expose launch-bound agent tools", "floati mcp serve --root ROOT --as NODE --session SESSION", "Serve only the generated Floati tool surface over local standard input and output.", "    Subcommand: serve. No network transport or identity override exists.", "    floati mcp serve --root ~/fleet --as builder-a --session codex-session"),
    "mcp serve": _page("floati mcp serve - serve one launch-bound MCP session", "floati mcp serve --root ROOT --as NODE --session SESSION", "Read newline-delimited MCP requests from standard input and write only MCP responses to standard output.", "    --root ROOT       Existing explicit fleet root.\n    --as NODE         Exact registered node bound for the process lifetime.\n    --session SESSION Exact acting harness session bound for the process lifetime.\n    The transport opens no listener and emits no non-protocol standard output.", "    floati mcp serve --root ~/fleet --as builder-a --session codex-session"),
    "sequencer": _page("floati sequencer - manage the optional local writer", "floati sequencer {status|serve|direct} [OPTIONS]", "Observe or explicitly transition the host-local run sequencer. No raw record operation exists.", "    Subcommands: status, serve, direct. Use a subcommand --help for its exact contract.", "    floati sequencer status --root ~/fleet"),
    "sequencer status": _page("floati sequencer status - observe local writer mode", "floati sequencer status --root ROOT", "Read durable epoch evidence and host-local lock/socket testimony without creating files.", "    --root ROOT   Explicit direct-home fleet root.", "    floati sequencer status --root ~/fleet"),
    "sequencer serve": _page("floati sequencer serve - run the local managed writer", "floati sequencer serve --root ROOT --as ID [--takeover]", "Hold one exclusive owner lease for the service lifetime and release it on graceful shutdown.", "    --root ROOT   Explicit direct-home fleet root.\n    --as ID       Bounded sequencer identity.\n    --takeover    Required only when open durable evidence remains after owner absence.", "    floati sequencer serve --root ~/fleet --as local-writer"),
    "sequencer direct": _page("floati sequencer direct - restore daemonless writer mode", "floati sequencer direct --root ROOT --as ID", "Prove exclusive host-local owner absence and atomically close abandoned managed evidence before returning.", "    --root ROOT   Explicit direct-home fleet root.\n    --as ID       Bounded operator transition identity.", "    floati sequencer direct --root ~/fleet --as operator-a"),
    "install": _page(
        "floati install - install the exact governed bundle",
        "floati install --source SOURCE --destination DESTINATION [--ref REF] [--committed-tree] [--json]",
        "Install only the exact files named by the source bundle manifest after a currency check in the writer.",
        "    --source SOURCE          Absolute committed source checkout.\n    --destination PATH       Absolute install destination.\n    --ref REF                Named Git ref; default origin/main.\n    --committed-tree         Explicit committed-tree CI mode.\n    --json emits the same safe lifecycle artifact without terminal rendering.\n    Foreign files are preserved; the writer never-prune-foreign.",
        "    floati install --source /repo/floati --destination /opt/floati --ref origin/main\n    floati install --source /repo/floati --destination ~/floati --committed-tree",
    ),
    "update": _page(
        "floati update - update the exact governed bundle",
        "floati update (--source SOURCE --destination DESTINATION [OPTIONS] | fleet {preview|apply} [OPTIONS])",
        "Update one exact governed bundle, or plan/apply one explicit fleet-wide update against caller-named external bindings.",
        "    --source SOURCE          Absolute committed source checkout for legacy single-install update.\n    --destination PATH       Absolute install destination.\n    --ref REF                Named Git ref; default origin/main.\n    --committed-tree         Explicit committed-tree CI mode.\n    fleet                    Explicit read-only preview or consent-gated fleet apply.\n    --json emits the same safe lifecycle artifact without terminal rendering.\n    Foreign files are preserved; the writer never-prune-foreign.",
        "    floati update --source /repo/floati --destination /opt/floati --ref origin/main\n    floati update fleet preview --help",
    ),
    "update fleet": _page(
        "floati update fleet - plan or apply one explicit fleet-wide update",
        "floati update fleet {preview|apply} [OPTIONS]",
        "Operate only the fleet root, installation, waiter inventory, registry, and transport named by the caller; no ambient discovery occurs.",
        "    Subcommands: preview, apply. Preview is physically read-only. Apply requires the exact preview digest and an idempotency key.",
        "    floati update fleet preview --help\n    floati update fleet apply --help",
    ),
    "update fleet preview": _page(
        "floati update fleet preview - derive one immutable fleet update plan",
        "floati update fleet preview --root ROOT --as NODE --destination INSTALL --channel CHANNEL --version VERSION --waiter-binding BINDING.json --transport-registry REGISTRY.json --transport TRANSPORT [--json]",
        "Re-open and digest every explicitly named installation, waiter, configuration, inventory, and registry byte without locking or writing.",
        "    --root ROOT                    Exact fleet direct home.\n    --as NODE                      Exact acting node.\n    --destination INSTALL          Exact shared installation.\n    --channel CHANNEL              Exact signed HTTPS release channel.\n    --version VERSION              Exact release version.\n    --waiter-binding BINDING.json  Strict caller-named waiter inventory.\n    --transport-registry PATH      Exact host transport registry.\n    --transport TRANSPORT          Exact selected transport.\n    --json                          Emit the compact artifact contract.\n    No automatic, discovery, or mutation option exists.",
        "    floati update fleet preview --root ~/fleet --as builder-a --destination /opt/floati --channel https://updates.example/release-index.v0 --version 2.0.0 --waiter-binding ~/BINDING.json --transport-registry ~/profiles.json --transport floati-installed-v0 --json",
    ),
    "update fleet apply": _page(
        "floati update fleet apply - apply one consented immutable fleet update plan",
        "floati update fleet apply --root ROOT --as NODE --destination INSTALL --channel CHANNEL --version VERSION --waiter-binding BINDING.json --transport-registry REGISTRY.json --transport TRANSPORT --plan-digest SHA256 --idempotency-key KEY [--json]",
        "Re-plan every named byte, require an exact digest match and active AU-1 consent, then enter the resumable receipt saga.",
        "    --root ROOT                    Exact fleet direct home.\n    --as NODE                      Exact acting node.\n    --destination INSTALL          Exact shared installation.\n    --channel CHANNEL              Exact signed HTTPS release channel.\n    --version VERSION              Exact release version.\n    --waiter-binding BINDING.json  Strict caller-named waiter inventory.\n    --transport-registry PATH      Exact host transport registry.\n    --transport TRANSPORT          Exact selected transport.\n    --plan-digest SHA256           Exact digest emitted by preview.\n    --idempotency-key KEY          Exact resumable operation key.\n    --json                          Emit the compact artifact contract.\n    No automatic, discovery, raw-pin, or implicit-consent option exists.",
        "    floati update fleet apply --root ~/fleet --as builder-a --destination /opt/floati --channel https://updates.example/release-index.v0 --version 2.0.0 --waiter-binding ~/BINDING.json --transport-registry ~/profiles.json --transport floati-installed-v0 --plan-digest <digest> --idempotency-key fu1-001 --json",
    ),
    "uninstall": _page("floati uninstall - remove exact owned tool bytes", "floati uninstall --destination PATH [--dry-run] [--json]", "Remove only unchanged manifest-owned tool files while retaining bus roots, ledgers, and foreign files.", "    --destination PATH   Existing absolute installed bundle.\n    --dry-run            Validate and preview without removing files.\n    --json emits the same safe lifecycle artifact without terminal rendering.", "    floati uninstall --destination /opt/floati --dry-run"),
    "purge": _page("floati purge - move the exact roots you list into the account Trash; never deletes", "floati purge (--root ROOT | --preserved-root ROOT) [...] [--dry-run]", "Move the exact roots you list into the account Trash; never deletes.", "    --root ROOT             one absolute preserved root to move; repeat for more\n    --preserved-root ROOT   alias of --root\n    --dry-run               list every file that would move; move nothing", "    floati purge --root ~/fleet --dry-run"),
}

HELP: Dict[str, str] = {
    topic: register("help.root" if not topic else "help." + topic.replace(" ", "."), text, "CLI help")
    for topic, text in _RAW.items()
}


def name_line_description(topic: str) -> str:
    """The approved one-line description from a topic's NAME line, for derived surfaces."""
    page = _RAW.get(topic)
    if page is None:
        raise KeyError(f"no help page for topic {topic!r}")
    name_line = page.splitlines()[1].strip()
    prefix, separator, description = name_line.partition(" - ")
    if not separator or not description:
        raise ValueError(f"help NAME line for {topic!r} carries no description")
    return description


def help_for(arguments: Sequence[str]) -> Optional[str]:
    if "--help" not in arguments:
        return None
    if not arguments or arguments[0] == "--help":
        topic = ""
    elif arguments[0] == "overlap" and len(arguments) > 1 and arguments[1] == "report":
        topic = "overlap report"
    elif arguments[0] == "work" and len(arguments) > 1 and arguments[1] in {"add", "claim", "complete", "show"}:
        topic = "work " + arguments[1]
    elif arguments[0] == "intake" and len(arguments) > 1 and arguments[1] == "scan":
        topic = "intake scan"
    elif arguments[0] == "intake" and len(arguments) > 1 and arguments[1] == "show":
        topic = "intake show"
    elif arguments[0] == "intake" and len(arguments) > 1 and arguments[1] in {"adopt", "preview", "dispatch"}:
        topic = "intake " + arguments[1]
    elif arguments[0] == "worker" and len(arguments) > 1 and arguments[1] == "run":
        topic = "worker run"
    elif arguments[0] == "sequencer" and len(arguments) > 1 and arguments[1] in {"status", "serve", "direct"}:
        topic = "sequencer " + arguments[1]
    elif arguments[0] == "journal" and len(arguments) > 1 and arguments[1] in {"checkpoint", "verify"}:
        topic = "journal " + arguments[1]
    elif arguments[0] == "signature" and len(arguments) > 1 and arguments[1] in {"sign", "verify"}:
        topic = "signature " + arguments[1]
    elif arguments[0] == "repair" and len(arguments) > 1 and arguments[1] == "quarantine":
        topic = "repair quarantine"
    elif arguments[0] == "mcp" and len(arguments) > 1 and arguments[1] == "serve":
        topic = "mcp serve"
    elif arguments[0] == "effect" and len(arguments) > 1 and arguments[1] in {"show", "reconcile", "compensate"}:
        topic = "effect " + arguments[1]
    elif arguments[0] == "grant" and len(arguments) > 1 and arguments[1] == "revoke":
        topic = "grant revoke"
    elif arguments[0] == "thread" and len(arguments) > 1 and arguments[1] in {"attach", "observe", "detach", "show"}:
        topic = "thread " + arguments[1]
    elif arguments[0] == "node" and len(arguments) > 1 and arguments[1] in {"add", "spawn", "retire", "switch", "role", "boot", "teardown", "explain", "state-flush"}:
        topic = "node " + arguments[1]
    elif arguments[0] == "role" and len(arguments) > 1 and arguments[1] in {"list", "show"}:
        topic = "role " + arguments[1]
    elif arguments[0] == "quota" and len(arguments) > 1 and arguments[1] in {"collect", "show"}:
        topic = "quota " + arguments[1]
    elif arguments[0] == "context" and len(arguments) > 1:
        if arguments[1] in {"status", "turnover"}:
            topic = "context " + arguments[1]
        elif arguments[1] == "policy":
            if len(arguments) > 2 and arguments[2] in {"set", "show", "clear"}:
                topic = "context policy " + arguments[2]
            else:
                topic = "context policy"
        elif arguments[1] == "reading":
            if len(arguments) > 2 and arguments[2] == "record":
                topic = "context reading record"
            else:
                topic = "context reading"
        else:
            topic = "context"
    elif arguments[0] == "epoch" and len(arguments) > 1 and arguments[1] == "roll":
        topic = "epoch roll"
    elif arguments[0] == "wake" and len(arguments) > 1 and arguments[1] == "daemon":
        if len(arguments) > 2 and arguments[2] in {"consent", "bind", "install", "start", "status", "stop", "remove", "revoke"}:
            topic = "wake daemon " + arguments[2]
        else:
            topic = "wake daemon"
    elif arguments[0] == "wake" and len(arguments) > 1 and arguments[1] in {"arm", "pause", "resume", "status"}:
        topic = "wake " + arguments[1]
    elif arguments[0] == "update" and len(arguments) > 1 and arguments[1] == "fleet":
        if len(arguments) > 2 and arguments[2] in {"preview", "apply"}:
            topic = "update fleet " + arguments[2]
        else:
            topic = "update fleet"
    elif arguments[0] == "confluence" and len(arguments) > 1 and arguments[1] in {"grant", "revoke", "status", "bundle", "adopt", "release"}:
        topic = "confluence " + arguments[1]
    elif arguments[0] == "presence" and len(arguments) > 1 and arguments[1] in {"report", "show"}:
        topic = "presence " + arguments[1]
    else:
        topic = arguments[0]
    return HELP.get(topic)
