"""Static, instant, man-page-quality help for every Phase B command."""

from __future__ import annotations

from typing import Dict, Optional, Sequence

from .copy import register


def _page(name: str, synopsis: str, description: str, details: str, examples: str) -> str:
    return (
        f"NAME\n    {name}\n\n"
        f"SYNOPSIS\n    {synopsis}\n\n"
        f"DESCRIPTION\n    {description}\n\n"
        f"OPTIONS AND ARGUMENTS\n{details}\n\n"
        "EXIT STATUS\n"
        "    0 success; 20 refusal; 31 intentional silence; 32 no result;\n"
        "    33 malformed evidence; 34 orchestration deadline; 35 degraded.\n"
        "    The artifact process status is authoritative.\n\n"
        f"EXAMPLES\n{examples}\n"
    )


_RAW: Dict[str, str] = {
    "": _page(
        "floati - inspect and operate an explicit fleet root",
        "floati COMMAND [OPTIONS]",
        "Operate the local receipt-ledger bus and orchestration log. Every durable command requires an explicit root.",
        "    Commands: init, register, retire, node, role, context, chart, survey, wake, send,\n    inbox, ack, log, status, effects, effect, threads, thread, graph, plan,\n    doctor, watch, receipts, grant, work, worker, sequencer, supervise,\n    board, orchestrate, install, update, uninstall, purge. Use COMMAND --help for its contract.",
        "    floati status --root /absolute/fleet\n    floati effects --root /absolute/fleet\n    floati work --help",
    ),
    "init": _page("floati init - create a direct fleet home", "floati init [--root ROOT] [--solo NODE [--harness HARNESS]]", "Create or validate one explicit direct-home fleet root. Solo bootstrap registers one harness and a bounded work authority.", "    --root ROOT        Absolute direct-home path. Namespace roots are refused.\n    --solo NODE        Configure one unambiguous local work identity.\n    --harness HARNESS  Recorded harness role; default solo.", "    floati init --root /var/tmp/floati-demo\n    floati init --root /var/tmp/my-sessions --solo me --harness Codex"),
    "node": _page("floati node - node administration", "floati node {add|retire|switch|role|boot|teardown|explain|state-flush} [OPTIONS]", "Preview exact registry rows before committing lifecycle changes and project live node context without cached topology.", "    Subcommands: add, retire, switch, role, boot, teardown, explain, state-flush.", "    floati node add --root /var/tmp/fleet --node lane-a --harness Codex --lifetime permanent"),
    "node add": _page("floati node add - add one node", "floati node add --root ROOT --node NODE --harness HARNESS --lifetime permanent|temporary [--lease-minutes N]", "Preview and atomically commit an active registry row and optional lease, creating the nested workspace.", "    Temporary nodes require --lease-minutes; permanent nodes refuse it.", "    floati node add --root /var/tmp/fleet --node lane-a --harness Codex --lifetime temporary --lease-minutes 60"),
    "node retire": _page("floati node retire - retire one node", "floati node retire --root ROOT --node NODE", "Preview retirement rows and retain the node workspace.", "    Retirement never deletes the workspace or state vessel.", "    floati node retire --root /var/tmp/fleet --node lane-a"),
    "node switch": _page("floati node switch - switch provider assignment", "floati node switch --root ROOT --node NODE --harness HARNESS --model MODEL", "Preview and atomically commit the replacement registry row and provider receipt.", "    No model call, fallback, or credential operation occurs.", "    floati node switch --root /var/tmp/fleet --node lane-a --harness Cursor --model gpt-5.6"),
    "node role": _page("floati node role - assign a shipped role", "floati node role --root ROOT --node NODE --template ROLE --answer KEY=VALUE [...]", "Answer only declared template questions and preview the exact typed role record.", "    Answers must exactly match the selected template questions.", "    floati node role --root /var/tmp/fleet --node lane-a --template builder --answer repo=floati --answer never_touch=foreign-bus --answer reports_to=architect-a"),
    "node boot": _page("floati node boot - project live boot context", "floati node boot --root ROOT --node NODE --declared-roots FILE --managed-executable COMMAND --profile PROFILE [--json]", "Re-read live registry, role, topology, wake, and managed-bus evidence for one boot projection.", "    This command prints a projection; it does not launch a harness.", "    floati node boot --root /var/tmp/fleet --node lane-a --declared-roots /var/tmp/declared.json --managed-executable /usr/local/bin/floati-fleet --profile lane-a --json"),
    "node teardown": _page("floati node teardown - project the retention ritual", "floati node teardown --root ROOT --node NODE --declared-roots FILE --managed-executable COMMAND --profile PROFILE [--json]", "Re-read live evidence and project the ordered state-preserving teardown ritual.", "    Projection does not retire a node, close a lease, or delete a workspace.", "    floati node teardown --root /var/tmp/fleet --node lane-a --declared-roots /var/tmp/declared.json --managed-executable /usr/local/bin/floati-fleet --profile lane-a --json"),
    "node explain": _page("floati node explain - explain one live node", "floati node explain --root ROOT --node NODE --declared-roots FILE --managed-executable COMMAND --profile PROFILE [--json]", "Explain one node from a fresh boot projection and typed role provenance.", "    No state-file content, model, network, or foreign root is read.", "    floati node explain --root /var/tmp/fleet --node lane-a --declared-roots /var/tmp/declared.json --managed-executable /usr/local/bin/floati-fleet --profile lane-a --json"),
    "node state-flush": _page("floati node state-flush - receipt one state flush", "floati node state-flush --root ROOT --node NODE [--prior-mtime-ns NS]", "Observe canonical STATE.md metadata and return a content-free flush receipt.", "    The file is never parsed or copied; an optional prior mtime must be exceeded.", "    floati node state-flush --root /var/tmp/fleet --node lane-a"),
    "role": _page("floati role - inspect shipped role templates", "floati role {list|show} [OPTIONS]", "Read the typed shipped role library without model or network access.", "    Subcommands: list, show.", "    floati role list --root /var/tmp/fleet"),
    "role list": _page("floati role list - list shipped roles", "floati role list --root ROOT", "List the shipped typed role names.", "    --root ROOT   Existing explicit fleet root.", "    floati role list --root /var/tmp/fleet"),
    "role show": _page("floati role show - show one shipped role", "floati role show --root ROOT ROLE", "Show one immutable typed template and its digest.", "    ROLE   Exact shipped role name.", "    floati role show --root /var/tmp/fleet architect"),
    "context": _page("floati context - inspect context evidence and manage Tide signals", "floati context {status|turnover|policy|reading}", "Inspect cited harness evidence, project the read-only turnover ritual, or manage optional Tide policy and testimony.", "    Subcommands: status, turnover, policy, reading. Status and turnover are read-only; policy and reading use durable Tide ledgers.", "    floati context status --root /var/tmp/fleet --as lane-a --json"),
    "context status": _page("floati context status - report harness evidence", "floati context status --root ROOT --as NODE [--json]", "Report the selected node's citation-bound external context evidence.", "    --root ROOT   Existing explicit fleet root.\n    --as NODE     Exact active node whose recorded harness is projected.\n    --json        Emit the compact artifact twin.\n    This physically read-only projection never invents a measurement.", "    floati context status --root /var/tmp/fleet --as lane-a --json"),
    "context turnover": _page("floati context turnover - project the turnover ritual", "floati context turnover --root ROOT --as NODE [--json]", "Project teardown, metadata-only state flush, and successor boot in order.", "    --root ROOT   Existing explicit fleet root.\n    --as NODE     Exact active node whose live role provenance is projected.\n    --json        Emit the compact artifact twin.\n    The recipe prints command argv and performs no step.", "    floati context turnover --root /var/tmp/fleet --as lane-a --json"),
    "context policy": _page("floati context policy - manage Tide context policy", "floati context policy {set|show|clear}", "Set, inspect, or clear one optional node-bound Tide policy.", "    Subcommands: set, show, clear. Mutations require an explicit idempotency key.", "    floati context policy show --root /var/tmp/fleet --node lane-a --json"),
    "context policy set": _page("floati context policy set - set one Tide policy", "floati context policy set --root ROOT --node NODE --metric METRIC --threshold THRESHOLD --action recommend|direct --idempotency-key KEY [--json]", "Append one exact node-bound policy to the durable Tide policy ledger.", "    --root ROOT               Existing explicit fleet root.\n    --node NODE               Exact active node.\n    --metric METRIC           Ruled Tide metric.\n    --threshold THRESHOLD     Metric threshold text.\n    --action recommend|direct Ruled action.\n    --idempotency-key KEY     Stable replay key.\n    --json                    Emit the compact artifact twin.", "    floati context policy set --root /var/tmp/fleet --node lane-a --metric context_fraction --threshold 20% --action recommend --idempotency-key tide-1 --json"),
    "context policy show": _page("floati context policy show - show one Tide policy", "floati context policy show --root ROOT --node NODE [--json]", "Read the active node-bound Tide policy or return its typed absence.", "    --root ROOT   Existing explicit fleet root.\n    --node NODE   Exact active node.\n    --json        Emit the compact artifact twin.", "    floati context policy show --root /var/tmp/fleet --node lane-a --json"),
    "context policy clear": _page("floati context policy clear - clear one Tide policy", "floati context policy clear --root ROOT --node NODE --idempotency-key KEY [--json]", "Append an exact clearing record for one active node-bound Tide policy.", "    --root ROOT               Existing explicit fleet root.\n    --node NODE               Exact active node.\n    --idempotency-key KEY     Stable replay key.\n    --json                    Emit the compact artifact twin.", "    floati context policy clear --root /var/tmp/fleet --node lane-a --idempotency-key tide-clear-1 --json"),
    "context reading": _page("floati context reading - record seated context testimony", "floati context reading {record}", "Manage bounded Class-B context testimony from a seated node.", "    Subcommands: record. A reading records testimony; it does not create an external measurement.", "    floati context reading record --root /var/tmp/fleet --as lane-a --metric self_reported_context_fraction --value 42% --command /context --idempotency-key reading-1 --json"),
    "context reading record": _page("floati context reading record - append context testimony", "floati context reading record --root ROOT --as NODE --metric METRIC --value VALUE --command /context|/status|/usage|/cost --idempotency-key KEY [--json]", "Append one exact seated-node testimony row to the durable Tide testimony ledger.", "    --root ROOT               Existing explicit fleet root.\n    --as NODE                 Exact seated node.\n    --metric METRIC           Ruled Tide metric.\n    --value VALUE             Testified value text.\n    --command COMMAND         Exact supported slash-command source.\n    --idempotency-key KEY     Stable replay key.\n    --json                    Emit the compact artifact twin.", "    floati context reading record --root /var/tmp/fleet --as lane-a --metric self_reported_context_fraction --value 42% --command /context --idempotency-key reading-1 --json"),
    "chart": _page("floati chart - multi-bus Harbor Chart", "floati chart --declared-roots FILE [--json]", "Read only explicitly declared roots and validated ledgers; never discover roots.", "    --declared-roots FILE   Required absolute declarations file.\n    --json                  Emit the compact artifact twin.", "    floati chart --declared-roots /var/tmp/declared.json --json"),
    "survey": _page("floati survey - read-only foreign-bus survey", "floati survey --declared-roots FILE [--search-path PATH] [--hooks FILE] [--targets FILE] [--json]", "Survey one explicit bounded request without writing, draining, acknowledging, registering, or locking a foreign bus.", "    --search-path PATH   Repeatable explicit directory.\n    --hooks FILE         Optional explicit hook JSON.\n    --targets FILE       Repeatable explicit target JSON.", "    floati survey --declared-roots /var/tmp/declared.json --search-path /var/tmp --json"),
    "wake": _page("floati wake - control exact wake coordinates", "floati wake {arm|pause|resume|status|daemon} [OPTIONS]", "Arm one exact acting session, control one exact session marker, or manage one consented local wake daemon coordinate.", "    Global and wildcard selectors do not exist. Use a subcommand --help for its exact contract.", "    floati wake arm --root /var/tmp/fleet --as lane-a --session codex-session --workspace /repo --idempotency-key arm-1"),
    "wake arm": _page("floati wake arm - arm one exact acting session", "floati wake arm --root ROOT --as NODE --session SESSION --workspace PATH --idempotency-key KEY", "Append an initial arm or predecessor-bound takeover for one consented workspace binding.", "    The actor must own the exact mapped workspace. Re-arming replaces only the prior session authority and leaves hook registration unchanged.", "    floati wake arm --root /var/tmp/fleet --as lane-a --session codex-session --workspace /repo --idempotency-key arm-1"),
    "wake pause": _page("floati wake pause - pause one exact session", "floati wake pause --root ROOT --as NODE --session SESSION", "Record a pause receipt and commit one exact session marker.", "    Paused is a recorded state, not absence or deafness.", "    floati wake pause --root /var/tmp/fleet --as lane-a --session 01a0..."),
    "wake resume": _page("floati wake resume - resume one exact session", "floati wake resume --root ROOT --as NODE --session SESSION", "Record the symmetric resume request and remove only the exact pause marker.", "    Hook registration and every other session remain unchanged.", "    floati wake resume --root /var/tmp/fleet --as lane-a --session 01a0..."),
    "wake status": _page("floati wake status - inspect one exact session", "floati wake status --root ROOT --as NODE --session SESSION", "Report active or paused and name the running session cache and harness trust gate as unknown.", "    Status is physically read-only and never infers deafness from a pause.", "    floati wake status --root /var/tmp/fleet --as lane-a --session 01a0..."),
    "wake daemon": _page("floati wake daemon - manage one local wake daemon", "floati wake daemon {consent|bind|install|start|status|stop|remove|revoke} [OPTIONS]", "Manage one exact node and harness coordinate with explicit consent and digest-bound local evidence.", "    Public subcommands do not accept arbitrary commands, fallback roots, or global selectors.", "    floati wake daemon status --root /var/tmp/fleet --as lane-a --harness cursor"),
    "wake daemon consent": _page("floati wake daemon consent - record exact activation consent", "floati wake daemon consent --root ROOT --as NODE --harness codex|cursor --min-poll-seconds N --max-poll-seconds N --max-backoff-seconds N --activation-epoch N", "Record bounded polling consent for one exact adapter contract.", "    Consent records evidence only; it does not install or invoke launchctl.", "    floati wake daemon consent --root /var/tmp/fleet --as lane-a --harness cursor --min-poll-seconds 1 --max-poll-seconds 30 --max-backoff-seconds 120 --activation-epoch 1"),
    "wake daemon bind": _page("floati wake daemon bind - bind one Cursor session", "floati wake daemon bind --root ROOT --as NODE --harness cursor --session SESSION --workspace PATH --executable PATH --binding-epoch N", "Record one exact Cursor session, workspace, and executable digest.", "    Codex bindings are accepted only from the trusted waiter and are refused here.", "    floati wake daemon bind --root /var/tmp/fleet --as lane-a --harness cursor --session SESSION --workspace /repo --executable /opt/homebrew/bin/cursor-agent --binding-epoch 1"),
    "wake daemon install": _page("floati wake daemon install - install the exact LaunchAgent", "floati wake daemon install --root ROOT --as NODE --harness codex|cursor", "Install deterministic digest-bound plist bytes without starting them.", "    Installation requires active consent and an exact adapter binding; it does not invoke launchctl.", "    floati wake daemon install --root /var/tmp/fleet --as lane-a --harness cursor"),
    "wake daemon start": _page("floati wake daemon start - start the exact LaunchAgent", "floati wake daemon start --root ROOT --as NODE --harness codex|cursor", "Bootstrap and kickstart only the deterministic user-domain LaunchAgent.", "    A missing or changed plist is a typed refusal.", "    floati wake daemon start --root /var/tmp/fleet --as lane-a --harness cursor"),
    "wake daemon status": _page("floati wake daemon status - inspect one daemon coordinate", "floati wake daemon status --root ROOT --as NODE --harness codex|cursor", "Report inactive before consent and otherwise inspect only the exact installed supervisor coordinate.", "    Inactive status is physically read-only and does not create daemon state.", "    floati wake daemon status --root /var/tmp/fleet --as lane-a --harness cursor"),
    "wake daemon stop": _page("floati wake daemon stop - stop the exact LaunchAgent", "floati wake daemon stop --root ROOT --as NODE --harness codex|cursor", "Request bootout and prove process absence for one exact user-domain label.", "    Unproven process absence is reported as unknown.", "    floati wake daemon stop --root /var/tmp/fleet --as lane-a --harness cursor"),
    "wake daemon remove": _page("floati wake daemon remove - remove the exact LaunchAgent", "floati wake daemon remove --root ROOT --as NODE --harness codex|cursor", "Quarantine and remove only matching deterministic plist bytes.", "    Removal refuses symlinks, inode changes, and digest drift.", "    floati wake daemon remove --root /var/tmp/fleet --as lane-a --harness cursor"),
    "wake daemon revoke": _page("floati wake daemon revoke - revoke exact daemon consent", "floati wake daemon revoke --root ROOT --as NODE --harness codex|cursor", "Stop and remove matching supervisor bytes, then append exact consent revocation.", "    If process absence cannot be proved, final state remains unknown.", "    floati wake daemon revoke --root /var/tmp/fleet --as lane-a --harness cursor"),
    "register": _page("floati register - register this node", "floati register --root ROOT NODE --harness HARNESS", "Append one active node registration. A node registers only itself.", "    --root ROOT         Explicit direct-home fleet root.\n    NODE                Bounded node identifier.\n    --harness HARNESS   Harness role recorded on disk.", "    floati register --root /var/tmp/fleet lane-a --harness Codex"),
    "retire": _page("floati retire - retire this node's registry row", "floati retire --root ROOT NODE", "Append one retirement row for the calling node, under the same lock register uses. Self-retirement only; the registered role carries forward and the ledger stays append-only. A retired node leaves the active roster; its history remains readable.", "    --root ROOT   Explicit direct-home fleet root.\n    NODE          The node retiring itself. Retiring another node (--as, --actor) is refused.", "    floati retire --root /var/tmp/fleet lane-a"),
    "send": _page("floati send - append a Git notification", "floati send --root ROOT --from NODE --to NODE --repo REPO --sha SHA --doc PATH --note TEXT [--reply-to ID] [--idempotency-key KEY]", "Send a Git-authoritative notification. Delivery and acknowledgment remain separate receipts.", "    --reply-to ID          Existing reversed-party message binding.\n    --idempotency-key KEY  Stable replay key; the effective key is echoed.\n    All routing and Git fields are required.", "    floati send --root /var/tmp/fleet --from a --to b --repo floati --sha <sha> --doc docs/evidence/checkpoint.md --note checkpoint"),
    "inbox": _page("floati inbox - present pending mail", "floati inbox --root ROOT --as NODE", "Present unacknowledged notifications and append an exact delivery receipt.", "    --root ROOT   Explicit fleet root.\n    --as NODE     Exact registered recipient.", "    floati inbox --root /var/tmp/fleet --as lane-a"),
    "ack": _page("floati ack - acknowledge one presented message", "floati ack --root ROOT --as NODE --session SESSION --id MESSAGE", "Append an actor-bound acknowledgment receipt. Acknowledgment does not claim action or completion.", "    --root ROOT       Explicit fleet root.\n    --as NODE         Exact recipient.\n    --session SESSION Exact acting harness session.\n    --id MESSAGE      Previously presented message identifier.", "    floati ack --root /var/tmp/fleet --as lane-a --session codex-session --id msg-..."),
    "grant": _page("floati grant - append exact work authority", "floati grant --root ROOT --as GRANTOR --holder NODE --subject SUBJECT --epoch N", "Grant one exact holder, subject, and epoch coordinate when GRANTOR has an active architect role record.", "    --root ROOT       Existing explicit fleet root.\n    --as GRANTOR      Active node with the architect role template.\n    --holder NODE     Exact active authority holder.\n    --subject SUBJECT Exact authority subject; wildcards do not exist.\n    --epoch N         Exact positive authority epoch.\n    Exact active-coordinate replay is idempotent; a higher epoch supersedes the prior coordinate.", "    floati grant --root /var/tmp/fleet --as architect-a --holder lane-a --subject work-claims --epoch 1"),
    "grant revoke": _page("floati grant revoke - revoke exact work authority", "floati grant revoke --root ROOT --as GRANTOR --holder NODE --subject SUBJECT --epoch N", "Revoke one exact authority coordinate under the same architect-role gate as grant.", "    --root ROOT       Existing explicit fleet root.\n    --as GRANTOR      Active node with the architect role template.\n    --holder NODE     Exact authority holder.\n    --subject SUBJECT Exact authority subject.\n    --epoch N         Exact current authority epoch.\n    Exact repeated revocation returns the durable revoking record.", "    floati grant revoke --root /var/tmp/fleet --as architect-a --holder lane-a --subject work-claims --epoch 1"),
    "log": _page("floati log - read mail or replay orchestration evidence", "floati log --root ROOT [--replay [--speed X] [--plain]]", "Read canonical ledgers. Replay renders receipt-derived orchestration events in deterministic order.", "    --root ROOT   Explicit fleet root.\n    --replay      Render claims, turns, degradations, denials, and completions.\n    --speed X     Interactive playback speed from 0.1 through 100; default 1.\n    --plain       Emit one faithful append-only timeline without sleeping.", "    floati log --root /var/tmp/fleet\n    floati log --root /var/tmp/fleet --replay --speed 4\n    floati log --root /var/tmp/fleet --replay --plain"),
    "status": _page("floati status - summarize the fleet", "floati status --root ROOT [--json]", "Emit one compact whole-fleet snapshot with three separate plane states, work counts, and receipt counts. --json selects the documented stable version-zero read contract.", "    --root ROOT   Explicit fleet root.\n    --json        Declare machine consumption of the version-zero contract.", "    floati status --root /var/tmp/fleet\n    floati status --root /var/tmp/fleet --json"),
    "effects": _page("floati effects - list projected effect status", "floati effects --root ROOT [--run RUN_ID] [--attempt ATTEMPT_ID]", "Read the deterministic version-one effect projection without creating files or locks.", "    --root ROOT           Existing explicit fleet root.\n    --run RUN_ID          Optional exact run UUIDv7 identifier.\n    --attempt ATTEMPT_ID  Optional exact attempt UUIDv7 identifier.", "    floati effects --root /var/tmp/fleet\n    floati effects --root /var/tmp/fleet --run run-... --attempt attempt-..."),
    "effect": _page("floati effect - inspect or operate one effect", "floati effect {show|reconcile|compensate} [OPTIONS]", "Use one typed operation identifier for read-only inspection, frozen-adapter reconciliation, or fail-closed compensation planning.", "    Subcommands: show, reconcile, compensate. Use a subcommand --help for its exact contract.\n    No raw record, adapter, result, credential, request body, or authority input exists.", "    floati effect show --root /var/tmp/fleet --operation effect-op-..."),
    "effect show": _page("floati effect show - inspect one exact effect", "floati effect show --root ROOT --operation OPERATION_ID", "Read one exact projected effect operation without creating files or locks.", "    --root ROOT                Existing explicit fleet root.\n    --operation OPERATION_ID  Exact effect operation UUIDv7 identifier.", "    floati effect show --root /var/tmp/fleet --operation effect-op-..."),
    "effect reconcile": _page("floati effect reconcile - reconcile one effect", "floati effect reconcile --root ROOT --operation OPERATION_ID", "Run only the reconciliation adapter frozen in durable effect intent, using the canonical repository policy at ROOT/FLOATI.toml.", "    --root ROOT                Existing explicit fleet root.\n    --operation OPERATION_ID  Exact effect operation UUIDv7 identifier.\n    No adapter or result override exists.", "    floati effect reconcile --root /var/tmp/fleet --operation effect-op-..."),
    "effect compensate": _page("floati effect compensate - request compensation planning", "floati effect compensate --root ROOT --operation OPERATION_ID (--preview | --confirm PLAN_DIGEST)", "Fail closed because this CLI has no durable compensation action specification from which to construct or recover the exact plan. Preview and confirmation report typed unavailability without writing.", "    --root ROOT                Existing explicit fleet root.\n    --operation OPERATION_ID  Exact effect operation UUIDv7 identifier.\n    --preview                  Request a physically read-only preview.\n    --confirm PLAN_DIGEST     Name one lowercase SHA-256 plan digest.\n    Exactly one mode is required; neither mode accepts plan fields or authority.", "    floati effect compensate --root /var/tmp/fleet --operation effect-op-... --preview\n    floati effect compensate --root /var/tmp/fleet --operation effect-op-... --confirm <digest>"),
    "threads": _page("floati threads - list registered thread observations", "floati threads --root ROOT", "Read registered threads only through a pull-only projection; provider status is not task state.", "    --root ROOT   Existing explicit fleet root. No provider inventory or mutation is performed.", "    floati threads --root /var/tmp/fleet"),
    "thread": _page("floati thread - operate one registered thread attachment", "floati thread {attach|observe|detach|show} [OPTIONS]", "Operate registered threads only through a pull-only source; provider status is not task state.", "    Subcommands: attach, observe, detach, show. No raw provider status, content, prompt, or task-state input exists.", "    floati thread show --root /var/tmp/fleet --attachment thread-attachment-..."),
    "thread attach": _page("floati thread attach - register one explicit provider thread", "floati thread attach --root ROOT --as NODE --thread THREAD_ID --work-item WORK_ID [--run RUN_ID --attempt ATTEMPT_ID]", "Register one exact Codex task coordinate without sampling provider state; registered threads only are observable later.", "    Supply a work item alone, or the exact run, work item, and attempt. The actor must be registered.", "    floati thread attach --root /var/tmp/fleet --as observer --thread <uuid> --work-item work-..."),
    "thread observe": _page("floati thread observe - pull one registered provider status", "floati thread observe --root ROOT --attachment ATTACHMENT_ID", "Perform one bounded pull-only read. Provider status is not task state.", "    No status, timestamp, flag, title, text, path, or raw JSON option exists.", "    floati thread observe --root /var/tmp/fleet --attachment thread-attachment-..."),
    "thread detach": _page("floati thread detach - stop future observations", "floati thread detach --root ROOT --as NODE --attachment ATTACHMENT_ID", "Append one durable detachment for a registered thread; provider state is not mutated.", "    --as NODE must name the exact registered detaching actor.", "    floati thread detach --root /var/tmp/fleet --as observer --attachment thread-attachment-..."),
    "thread show": _page("floati thread show - inspect one exact attachment", "floati thread show --root ROOT --attachment ATTACHMENT_ID", "Read one registered thread attachment without provider access or writes.", "    The exact attachment view may reveal its registered provider coordinate.", "    floati thread show --root /var/tmp/fleet --attachment thread-attachment-..."),
    "graph": _page("floati graph - render the Harbor Chart", "floati graph --root ROOT [--json]", "Render a deterministic fleet map from durable ledgers only. Human output composes frozen topology with counts-only traffic; --json emits frozen topology v0.", "    --root ROOT   Explicit fleet root.\n    --json        Emit the frozen version-zero topology artifact.", "    floati graph --root /var/tmp/fleet\n    floati graph --root /var/tmp/fleet --json"),
    "plan": _page("floati plan - explain read-only plan admission", "floati plan --plan PLAN --policy POLICY --explain [--json]", "Read-only plan admission reports admitted, refused, or needs_operator from hard limits.", "    --plan PLAN       Explicit absolute plan path.\n    --policy POLICY   Explicit absolute FLOATI.toml path.\n    --explain         Required read-only explanation.\n    --json            Declare machine consumption of the version-zero contract.", "    floati plan --plan /var/tmp/plan.json --policy /var/tmp/FLOATI.toml --explain --json"),
    "doctor": _page("floati doctor - diagnose root and bundle integrity", "floati doctor --root ROOT --source SOURCE [--ref REF] [--gateway-config PATH] [--profile PROFILE]", "Run physically read-only typed checks for root, registry, manifest, currency, symlink identity, the sole consumption coordinate, and an explicitly supplied local gateway config.", "    --root ROOT       Explicit fleet direct home.\n    --source SOURCE   Explicit Floati source checkout.\n    --ref REF         Named deployment currency ref; default origin/main.\n    --gateway-config PATH  Optional local stdio gateway v0 config; no discovery.\n    --profile PROFILE      Optional ruled profile (bus-only, orchestration), never inferred; bus-only expects live directories to be absent.\n    The installer-shadow check reads PATH as supplied; a PATH that omits the install scripts directory yields unknown, naming the blocked entry - a partial scan is never reported as no-shadowing.\n    Remediation is printed only when its currency prerequisites are established.", "    floati doctor --root /var/tmp/fleet --source /repo/floati --ref origin/lane/hm0 --gateway-config /var/tmp/gateway.json"),
    "watch": _page("floati watch - poll for fleet deltas", "floati watch --root ROOT [--interval SECONDS] [--iterations COUNT]", "Stream one artifact for the initial observation and each changed observation.", "    --interval SECONDS   Poll interval from 0.05 through 60; default 0.25.\n    --iterations COUNT   Bounded poll count; default continues until interrupted.", "    floati watch --root /var/tmp/fleet --interval 0.25 --iterations 20"),
    "receipts": _page("floati receipts - inspect node receipt history", "floati receipts NODE --root ROOT", "Read delivery, acknowledgment, and denial histories as distinct evidence.", "    NODE          Exact registered node.\n    --root ROOT   Explicit fleet root.", "    floati receipts lane-a --root /var/tmp/fleet"),
    "supervise": _page("floati supervise - report fleet health", "floati supervise --root ROOT", "Run a physically read-only report of liveness, authority, mutex, inbox depth, and stale leases.", "    --root ROOT   Explicit fleet root. No action option exists.", "    floati supervise --root /var/tmp/fleet"),
    "board": _page("floati board - open the TUI harbor board", "floati board (--root ROOT --session SESSION | --demo) [--no-animation]", "Render the keyboard-first fleet board. Live acknowledgment is actor-bound. Dumb terminals receive a distinguishable plain dump.", "    --root ROOT       Explicit fleet root.\n    --session SESSION Exact acting harness session for live acknowledgment.\n    --demo            Use a throwaway synthetic fleet.\n    --no-animation    Emit one final frame without terminal control.", "    floati board --root /var/tmp/fleet --session codex-session\n    floati board --demo --no-animation"),
    "orchestrate": _page("floati orchestrate - seed and run a worker fleet", "floati orchestrate --root ROOT --plan PLAN --adapter codex --deadline SECONDS [--no-animation]", "Seed a bounded work DAG, launch at least three workers, stream the receipt-derived board, and emit one final artifact.", "    --root ROOT       Explicit prepared fleet root with registrations and authority.\n    --plan PLAN       Absolute version-zero orchestration plan path.\n    --adapter codex   Exact governed live-worker adapter.\n    --deadline SECONDS  Overall deadline from 0.1 through 3600.\n    --no-animation    Stream distinguishable plain text frames.", "    floati orchestrate --root /var/tmp/fleet --plan /var/tmp/plan.json --adapter codex --deadline 120"),
    "work": _page("floati work - operate the orchestration log", "floati work {add|claim|complete|show} [OPTIONS]", "Operate work items independently from mail.", "    Subcommands: add, claim, complete, show. Use a subcommand --help for its exact contract.", "    floati work show --root /var/tmp/fleet"),
    "work add": _page("floati work add - append a work item", "floati work add --root ROOT --title TEXT [--owner NODE] [--needs WORK] [--workspace] [--repo REPO --sha SHA --doc PATH]", "Append one open work item with optional dependency edges and Git artifact binding.", "    Artifact options are all-or-none. --owner may be omitted only in a solo root.\n    --needs WORK  Require one existing work item; repeat for multiple dependencies.\n    --workspace   Add the ruled absolute workspace under the system temporary directory in floati-work/<work-id>/; the worker creates it.", "    floati work add --root /var/tmp/my-sessions --title 'record this session'\n    floati work add --root /var/tmp/fleet --title 'build board' --owner lane-a --needs work-..."),
    "work claim": _page("floati work claim - claim with authority", "floati work claim --root ROOT --id WORK [--as NODE --authority-subject SUBJECT --authority-epoch EPOCH] [--now TIME]", "Append a claim only when the exact authority holder and epoch are active. Solo roots may resolve the one configured identity and grant.", "    --as, --authority-subject, and --authority-epoch may be omitted only when solo resolution is unambiguous.\n    --now TIME   Optional UTC RFC3339 observation for deterministic operation.", "    floati work claim --root /var/tmp/my-sessions --id work-...\n    floati work claim --root /var/tmp/fleet --id work-... --as lane-a --authority-subject build --authority-epoch 1"),
    "work complete": _page("floati work complete - append completion", "floati work complete --root ROOT --id WORK [--as NODE] [--repo REPO --sha SHA --doc PATH] [--now TIME]", "Complete only a work item claimed by the exact actor and retain artifact bindings. Solo roots may resolve the configured actor.", "    Artifact options are all-or-none. --as may be omitted only in a solo root. --now accepts UTC RFC3339.", "    floati work complete --root /var/tmp/my-sessions --id work-...\n    floati work complete --root /var/tmp/fleet --id work-... --as lane-a"),
    "work show": _page("floati work show - project work state", "floati work show --root ROOT [--id WORK]", "Project all work items or one exact item from append-only records.", "    --id WORK   Optional exact work item identifier.", "    floati work show --root /var/tmp/fleet"),
    "worker": _page("floati worker - run one authority-checked worker", "floati worker run --root ROOT --as NODE --adapter claude|codex|pi", "Claim one owned open work item and record every worker transition as durable evidence.", "    Use worker run for the exact command contract.", "    floati worker run --root /var/tmp/fleet --as lane-a --adapter claude"),
    "worker run": _page("floati worker run - run one authority-checked worker", "floati worker run --root ROOT --as NODE --adapter claude|codex|pi", "Claim one owned open work item and record typed degradation without silent fallback.", "    --root ROOT      Explicit fleet root.\n    --as NODE        Exact registered worker node.\n    --adapter claude|codex|pi  Exact governed adapter.", "    floati worker run --root /var/tmp/fleet --as lane-a --adapter claude"),
    "sequencer": _page("floati sequencer - manage the optional local writer", "floati sequencer {status|serve|direct} [OPTIONS]", "Observe or explicitly transition the host-local run sequencer. No raw record operation exists.", "    Subcommands: status, serve, direct. Use a subcommand --help for its exact contract.", "    floati sequencer status --root /var/tmp/fleet"),
    "sequencer status": _page("floati sequencer status - observe local writer mode", "floati sequencer status --root ROOT", "Read durable epoch evidence and host-local lock/socket testimony without creating files.", "    --root ROOT   Explicit direct-home fleet root.", "    floati sequencer status --root /var/tmp/fleet"),
    "sequencer serve": _page("floati sequencer serve - run the local managed writer", "floati sequencer serve --root ROOT --as ID [--takeover]", "Hold one exclusive owner lease for the service lifetime and release it on graceful shutdown.", "    --root ROOT   Explicit direct-home fleet root.\n    --as ID       Bounded sequencer identity.\n    --takeover    Required only when open durable evidence remains after owner absence.", "    floati sequencer serve --root /var/tmp/fleet --as local-writer"),
    "sequencer direct": _page("floati sequencer direct - restore daemonless writer mode", "floati sequencer direct --root ROOT --as ID", "Prove exclusive host-local owner absence and atomically close abandoned managed evidence before returning.", "    --root ROOT   Explicit direct-home fleet root.\n    --as ID       Bounded operator transition identity.", "    floati sequencer direct --root /var/tmp/fleet --as operator-a"),
    "install": _page(
        "floati install - install the exact governed bundle",
        "floati install --source SOURCE --destination DESTINATION [--ref REF] [--committed-tree] [--json]",
        "Install only the exact files named by the source bundle manifest after a currency check in the writer.",
        "    --source SOURCE          Absolute committed source checkout.\n    --destination PATH       Absolute install destination.\n    --ref REF                Named Git ref; default origin/main.\n    --committed-tree         Explicit committed-tree CI mode.\n    --json emits the same safe lifecycle artifact without terminal rendering.\n    Foreign files are preserved; the writer never-prune-foreign.",
        "    floati install --source /repo/floati --destination /opt/floati --ref origin/main\n    floati install --source /repo/floati --destination /tmp/floati --committed-tree",
    ),
    "update": _page(
        "floati update - update the exact governed bundle",
        "floati update --source SOURCE --destination DESTINATION [--ref REF] [--committed-tree] [--json]",
        "Update only the exact files named by the source bundle manifest, removing only unchanged files previously owned by Floati.",
        "    --source SOURCE          Absolute committed source checkout.\n    --destination PATH       Absolute install destination.\n    --ref REF                Named Git ref; default origin/main.\n    --committed-tree         Explicit committed-tree CI mode.\n    --json emits the same safe lifecycle artifact without terminal rendering.\n    Foreign files are preserved; the writer never-prune-foreign.",
        "    floati update --source /repo/floati --destination /opt/floati --ref origin/main\n    floati update --source /repo/floati --destination /tmp/floati --committed-tree",
    ),
    "uninstall": _page("floati uninstall - remove exact owned tool bytes", "floati uninstall --destination PATH [--dry-run] [--json]", "Remove only unchanged manifest-owned tool files while retaining bus roots, ledgers, and foreign files.", "    --destination PATH   Existing absolute installed bundle.\n    --dry-run            Validate and preview without removing files.\n    --json emits the same safe lifecycle artifact without terminal rendering.", "    floati uninstall --destination /opt/floati --dry-run"),
    "purge": _page("floati purge - move the exact roots you list into the account Trash; never deletes", "floati purge (--root ROOT | --preserved-root ROOT) [...] [--dry-run]", "Move the exact roots you list into the account Trash; never deletes.", "    --root ROOT             one absolute preserved root to move; repeat for more\n    --preserved-root ROOT   alias of --root\n    --dry-run               list every file that would move; move nothing", "    floati purge --root /var/tmp/fleet --dry-run"),
}

HELP: Dict[str, str] = {
    topic: register("help.root" if not topic else "help." + topic.replace(" ", "."), text, "CLI help")
    for topic, text in _RAW.items()
}


def help_for(arguments: Sequence[str]) -> Optional[str]:
    if "--help" not in arguments:
        return None
    if not arguments or arguments[0] == "--help":
        topic = ""
    elif arguments[0] == "work" and len(arguments) > 1 and arguments[1] in {"add", "claim", "complete", "show"}:
        topic = "work " + arguments[1]
    elif arguments[0] == "worker" and len(arguments) > 1 and arguments[1] == "run":
        topic = "worker run"
    elif arguments[0] == "sequencer" and len(arguments) > 1 and arguments[1] in {"status", "serve", "direct"}:
        topic = "sequencer " + arguments[1]
    elif arguments[0] == "effect" and len(arguments) > 1 and arguments[1] in {"show", "reconcile", "compensate"}:
        topic = "effect " + arguments[1]
    elif arguments[0] == "grant" and len(arguments) > 1 and arguments[1] == "revoke":
        topic = "grant revoke"
    elif arguments[0] == "thread" and len(arguments) > 1 and arguments[1] in {"attach", "observe", "detach", "show"}:
        topic = "thread " + arguments[1]
    elif arguments[0] == "node" and len(arguments) > 1 and arguments[1] in {"add", "retire", "switch", "role", "boot", "teardown", "explain", "state-flush"}:
        topic = "node " + arguments[1]
    elif arguments[0] == "role" and len(arguments) > 1 and arguments[1] in {"list", "show"}:
        topic = "role " + arguments[1]
    elif arguments[0] == "context" and len(arguments) > 1:
        if arguments[1] in {"status", "turnover"}:
            topic = "context " + arguments[1]
        elif arguments[1] == "policy":
            if len(arguments) > 2 and arguments[2] in {"set", "show", "clear"}:
                topic = "context policy " + arguments[2]
            else:
                topic = "context policy"
        elif arguments[1] == "reading":
            if len(arguments) > 2 and arguments[2] == "record":
                topic = "context reading record"
            else:
                topic = "context reading"
        else:
            topic = "context"
    elif arguments[0] == "wake" and len(arguments) > 1 and arguments[1] == "daemon":
        if len(arguments) > 2 and arguments[2] in {"consent", "bind", "install", "start", "status", "stop", "remove", "revoke"}:
            topic = "wake daemon " + arguments[2]
        else:
            topic = "wake daemon"
    elif arguments[0] == "wake" and len(arguments) > 1 and arguments[1] in {"arm", "pause", "resume", "status"}:
        topic = "wake " + arguments[1]
    else:
        topic = arguments[0]
    return HELP.get(topic)
