"""LC-GEN: project per-seat lifecycle command files from the LC-1 taxonomy.

Ruling ``docs/rulings/2026-09-05-lc-1-lifecycle-taxonomy-ruling.md`` §LC-1d:
one generator verb (``node prompts``) projects, from the role template, the
harness adapter table and the LC-1 parity table, the per-seat command files.
Every projection opens with a header naming the generator, the harbor SHA
and "hand edits are overwritten"; regeneration is byte-stable; the LC-R3
reserved-name fence refuses product verbs and other bus families' prompt
names for every file name the adapter's pattern yields (LC-GEN-R1 a),
and a file already under ``--out`` that does not carry the generator
header is refused by path — only generator-headed files are overwritten
(LC-GEN-R1 b); and the generator writes ONLY under the caller's
``--out`` — it never installs.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
from pathlib import Path

from .admin_registry import RegistryAdminBackend
from .errors import ProtocolRefusal
from .role_library import RoleTemplateLibrary
from .role_templates import RoleTemplate
from .root import FloatiRoot, validate_identifier

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

#: The LC-1a closed verb set.
LIFECYCLE_VERBS: tuple[str, ...] = (
    "boot", "board", "drain", "pause", "resume", "prep-clear", "turnover",
)

#: Other bus families' prompt names (LC-R3); the product's own verbs are
#: DERIVED from describe's live registry rather than hand-typed.
BUS_FAMILY_NAMES: frozenset[str] = frozenset({"pausebus", "resumebus"})


def reserved_names() -> frozenset[str]:
    """Product verb names (from describe's live registry) + bus families."""

    from .cli import _parser
    from .command_contract import describe_parser

    names: set[str] = set(BUS_FAMILY_NAMES)
    for row in describe_parser(_parser())["commands"]:
        path = [str(part) for part in row["path"]]
        names.add(path[-1])
        if len(path) > 1:
            names.add("-".join(path))
    return frozenset(names)

#: The harness adapter table: where each harness keeps its seat prompts and
#: which lifecycle verbs are realized as files there (LC-1 §1, LC-1d). The
#: file-name stem is adapter data (`file_pattern`): a pattern that can
#: produce a bare reserved word is exactly the shape the reserved-name
#: fence inside ``project_prompts`` refuses (LC-GEN-R1 a).
HARNESS_ADAPTERS: dict[str, dict] = {
    "codex": {
        "prompts_dir": ".codex/prompts",
        "verbs": ("boot", "board", "drain", "pause", "resume", "prep-clear"),
        "file_pattern": "{verb}-{node}",
    },
    "claude": {
        "prompts_dir": ".claude/commands",
        "verbs": ("boot", "prep-clear", "board"),
        "file_pattern": "{verb}-{node}",
    },
    "zcode": {
        "prompts_dir": None,  # the projection is BOOT.md's verb section
        "verbs": ("boot", "prep-clear"),  # §1: the BOOT.md §clear calls prep-clear
        "file_pattern": "boot-{node}",
    },
}

#: Honest dashes with their receipts (LC-1b): a cell is a dash, never a
#: gap, when the harness cannot realize the verb today.
DASH_RECEIPTS: dict[tuple[str, str], str] = {
    ("codex", "turnover"): (
        "dash: WIND-DOWN then BOARD; the receipts link by the wake claim's "
        "predecessor id (LC-1 §1 TURNOVER)"
    ),
    ("claude", "drain"): (
        "dash: the product inbox/ack verbs run by hand; no file wrapper (LC-1 §1 DRAIN)"
    ),
    ("claude", "pause"): (
        "dash: no daemon binds Claude seats today (LC-1 §1 PAUSE/RESUME)"
    ),
    ("claude", "resume"): (
        "dash: no daemon binds Claude seats today (LC-1 §1 PAUSE/RESUME)"
    ),
    ("claude", "turnover"): (
        "dash: WIND-DOWN then BOARD; the receipts link by the wake claim's "
        "predecessor id (LC-1 §1 TURNOVER)"
    ),
    ("zcode", "board"): (
        "dash: the Stop-hook bridge injects at a turn end; seat board by hand "
        "(LC-1 §1 BOARD)"
    ),
    ("zcode", "drain"): "dash: the bridge drains at turn end (LC-1 §1 DRAIN)",
    ("zcode", "pause"): (
        "dash: wake pause/resume verbs by hand; no file wrapper (LC-1 §1 PAUSE/RESUME)"
    ),
    ("zcode", "resume"): (
        "dash: wake pause/resume verbs by hand; no file wrapper (LC-1 §1 PAUSE/RESUME)"
    ),
    ("zcode", "turnover"): (
        "dash: WIND-DOWN then BOARD; the receipts link by the wake claim's "
        "predecessor id (LC-1 §1 TURNOVER)"
    ),
}

_GIT_CANDIDATES = ("/usr/bin/git", "/bin/git")

#: Every file this generator writes opens with this marker; a file under
#: ``--out`` without it was not written here and is never overwritten.
GENERATED_MARKER = "<!-- generated by floati node prompts"

#: The LC-1 §1 product realization of each projected verb, as a command path
#: into the live parser. The rendered lines DERIVE from the parser's own
#: required options — never from prose.
VERB_COMMANDS: dict[str, tuple[tuple[str, ...], ...]] = {
    "boot": (("node", "spawn"),),
    "board": (("seat", "board"),),
    "drain": (("inbox",), ("ack",)),
    "pause": (("wake", "pause"),),
    "resume": (("wake", "resume"),),
    "prep-clear": (("node", "prep-clear"),),
}

_PROVIDED = ("--root", "--as")


def _subparser(path: tuple[str, ...]):
    from .cli import _parser

    parser = _parser()
    for name in path:
        for action in parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                parser = action.choices[name]
                break
    return parser


def _command_line(path: tuple[str, ...], root: str, node: str) -> str:
    """Render one invocation from the parser's own required options."""

    parser = _subparser(path)
    parts = ["floati", *path, "--root", root, "--as", node]
    for action in parser._actions:
        if not action.required or not action.option_strings:
            continue
        option = action.option_strings[0]
        if option in _PROVIDED:
            continue
        placeholder = (action.metavar or action.dest).upper().replace("-", "_")
        parts.extend([option, placeholder])
    return " ".join(parts)


def _verb_lines(verb: str, root: str, node: str) -> list[str]:
    lines = []
    for path in VERB_COMMANDS[verb]:
        lines.append(f"- `{_command_line(path, root, node)}`")
    return lines


def harbor_sha() -> str:
    """The running tree's HEAD SHA, git by the fixed candidate list."""

    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    for candidate in _GIT_CANDIDATES:
        if not os.access(candidate, os.X_OK):
            continue
        result = subprocess.run(
            [candidate, "rev-parse", "HEAD"],
            cwd=str(REPOSITORY_ROOT),
            env=env,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    raise ProtocolRefusal(
        "lifecycle_prompts_sha_absent",
        "the harbor SHA cannot be read: none of the fixed git candidates answered",
    )


def assert_no_collision(name: str) -> None:
    """LC-R3: a projected name may not claim a reserved name.

    Called by ``project_prompts`` for EVERY file name it is about to
    write, so the fence fires on whatever shape an adapter's pattern
    produces — a bare reserved word included (LC-GEN-R1 a). The reserved
    set is derived from describe's live registry plus the bus families
    and pinned by count in the contract test, so the fence tracks the
    product as its verb vocabulary moves.
    """

    if name in reserved_names():
        raise ProtocolRefusal(
            "lifecycle_prompts_name_reserved",
            f"{name!r} is claimed by the product's own verbs or another bus "
            "family's prompt set",
            remedy="project the file under a seat-suffixed name instead",
        )


def _file_stem(adapter: dict, verb: str, node: str) -> str:
    """The file-name stem one verb projects to, by the adapter's pattern."""

    return adapter["file_pattern"].format(verb=verb, node=node)


def _header(source: str, sha: str) -> str:
    return (
        f"{GENERATED_MARKER} ({source}) at harbor {sha}\n"
        "     hand edits are overwritten -->"
    )


def _write_projection(target: Path, content: str) -> None:
    """LC-GEN-R1 (b): only generator-headed files under --out are ours.

    A file already under the output directory without the marker is
    someone else's command file and is refused by path; a file WITH the
    marker is this generator's and is overwritten, as the header says.
    """

    if target.exists():
        existing = target.read_text(encoding="utf-8", errors="replace")
        if not existing.startswith(GENERATED_MARKER):
            raise ProtocolRefusal(
                "lifecycle_prompts_target_foreign",
                f"{target} exists under the output directory and does not "
                "carry the generator header; it is not this generator's file",
                remedy="project into an empty directory, or move the foreign file",
            )
    target.write_text(content, encoding="utf-8")


def _digest(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _verb_body(
    verb: str, node: str, role: dict, template: RoleTemplate, root_path: str
) -> str:
    duties = ", ".join(template.duties[:2])
    lines = [
        f"You are **{node}**, role `{role['template_role']}` "
        f"(template v{role['template_version']}, sha {role['template_sha256'][:12]}; "
        f"duties: {duties}).",
        "",
        f"**{verb.upper()}.**",
    ]
    lines.extend(_verb_lines(verb, root_path, node))
    lines.extend([
        "",
        "Fill the uppercase placeholders from your seat declaration, never "
        "from memory.",
    ])
    return "\n".join(lines)


def _zcode_section(node: str, sha: str, parity: dict[str, str], root_path: str) -> str:
    lines = [
        _header("BOOT.md verb section", sha),
        "",
        f"## Lifecycle verbs for {node}",
        "",
    ]
    for verb in LIFECYCLE_VERBS:
        cell = parity[verb]
        if cell.startswith("file:"):
            lines.append(f"- **{verb}**: realized by `{cell[5:]}` in this directory.")
        else:
            lines.append(f"- **{verb}**: {cell}")
    lines.append("")
    for verb in ("boot", "prep-clear"):
        lines.extend(_verb_lines(verb, root_path, node))
    return "\n".join(lines) + "\n"


def project_prompts(root: FloatiRoot, node: str, harness: str, out_dir: Path) -> dict:
    """Write the seat's lifecycle projections under ``out_dir`` and report."""

    adapter = HARNESS_ADAPTERS.get(harness)
    if adapter is None:
        raise ProtocolRefusal(
            "lifecycle_prompts_harness_unknown",
            f"harness {harness!r} has no adapter; known: "
            f"{', '.join(sorted(HARNESS_ADAPTERS))}",
        )
    node = validate_identifier(node, "node")
    backend = RegistryAdminBackend(root)
    entry = backend.active_node(node)
    if str(entry.get("role", "")).casefold() != harness.casefold():
        raise ProtocolRefusal(
            "lifecycle_prompts_harness_mismatch",
            f"node {node!r} is registered on harness {entry.get('role')!r}, "
            f"not {harness!r}",
        )
    role = backend.role_record(node)
    templates = RoleTemplateLibrary(root).templates()
    template = templates.get(str(role["template_role"]))
    if template is None:
        raise ProtocolRefusal(
            "role_template_unknown", "the node's role template is not shipped"
        )
    sha = harbor_sha()
    root_path = str(root.tenant_home)

    parity: dict[str, str] = {}
    for verb in LIFECYCLE_VERBS:
        if verb in adapter["verbs"]:
            stem = _file_stem(
                adapter, "boot" if harness == "zcode" else verb, node
            )
            parity[verb] = f"file:{stem}.md"
        elif (harness, verb) in DASH_RECEIPTS:
            parity[verb] = DASH_RECEIPTS[(harness, verb)]
        else:
            raise ProtocolRefusal(
                "lifecycle_prompts_parity_gap",
                f"verb {verb!r} on harness {harness!r} is neither realized nor "
                "an honest dash (LC-1 §1)",
            )

    out_dir.mkdir(parents=True, exist_ok=True)
    files: list[dict[str, str]] = []
    if harness == "zcode":
        stem = _file_stem(adapter, "boot", node)
        assert_no_collision(stem)
        content = _zcode_section(node, sha, parity, root_path)
        target = out_dir / f"{stem}.md"
        _write_projection(target, content)
        files.append({"path": target.name, "sha256": _digest(content)})
    else:
        for verb in adapter["verbs"]:
            stem = _file_stem(adapter, verb, node)
            assert_no_collision(stem)
            content = "\n".join([
                _header(f"{harness} {verb} prompt", sha),
                "",
                _verb_body(verb, node, role, template, root_path),
                "",
            ]) + "\n"
            target = out_dir / f"{stem}.md"
            _write_projection(target, content)
            files.append({"path": target.name, "sha256": _digest(content)})

    files.sort(key=lambda file_entry: file_entry["path"])
    return {
        "node": node,
        "harness": harness,
        "out": str(out_dir),
        "files": files,
        "parity": {harness: parity},
    }
